/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ApiNotFoundResponse,
    ApiNotFoundResponseFromJSON,
    ApiNotFoundResponseToJSON,
    CreateConsumerAcl,
    CreateConsumerAclFromJSON,
    CreateConsumerAclToJSON,
    CreateProducerAcl,
    CreateProducerAclFromJSON,
    CreateProducerAclToJSON,
    CreateStreamAppAcl,
    CreateStreamAppAclFromJSON,
    CreateStreamAppAclToJSON,
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    KafkaAcl,
    KafkaAclFromJSON,
    KafkaAclToJSON,
    KafkaAclNamePatternType,
    KafkaAclNamePatternTypeFromJSON,
    KafkaAclNamePatternTypeToJSON,
    KafkaAclResourceType,
    KafkaAclResourceTypeFromJSON,
    KafkaAclResourceTypeToJSON,
} from '../models';

export interface CreateAclRequest {
    clusterName: string;
    kafkaAcl: KafkaAcl;
}

export interface CreateConsumerAclRequest {
    clusterName: string;
    createConsumerAcl: CreateConsumerAcl;
}

export interface CreateProducerAclRequest {
    clusterName: string;
    createProducerAcl: CreateProducerAcl;
}

export interface CreateStreamAppAclRequest {
    clusterName: string;
    createStreamAppAcl: CreateStreamAppAcl;
}

export interface DeleteAclRequest {
    clusterName: string;
    kafkaAcl: KafkaAcl;
}

export interface GetAclAsCsvRequest {
    clusterName: string;
    resourceType?: KafkaAclResourceType;
    resourceName?: string;
    namePatternType?: KafkaAclNamePatternType;
    search?: string;
    fts?: boolean;
}

export interface ListAclsRequest {
    clusterName: string;
    resourceType?: KafkaAclResourceType;
    resourceName?: string;
    namePatternType?: KafkaAclNamePatternType;
    search?: string;
    fts?: boolean;
}

export interface SyncAclsCsvRequest {
    clusterName: string;
    body: string;
}

/**
 * AclsApi - interface
 * 
 * @export
 * @interface AclsApiInterface
 */
export interface AclsApiInterface {
    /**
     * 
     * @summary createAcl
     * @param {string} clusterName 
     * @param {KafkaAcl} kafkaAcl 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AclsApiInterface
     */
    createAclRaw(requestParameters: CreateAclRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * createAcl
     */
    createAcl(requestParameters: CreateAclRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary createConsumerAcl
     * @param {string} clusterName 
     * @param {CreateConsumerAcl} createConsumerAcl 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AclsApiInterface
     */
    createConsumerAclRaw(requestParameters: CreateConsumerAclRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * createConsumerAcl
     */
    createConsumerAcl(requestParameters: CreateConsumerAclRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary createProducerAcl
     * @param {string} clusterName 
     * @param {CreateProducerAcl} createProducerAcl 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AclsApiInterface
     */
    createProducerAclRaw(requestParameters: CreateProducerAclRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * createProducerAcl
     */
    createProducerAcl(requestParameters: CreateProducerAclRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary createStreamAppAcl
     * @param {string} clusterName 
     * @param {CreateStreamAppAcl} createStreamAppAcl 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AclsApiInterface
     */
    createStreamAppAclRaw(requestParameters: CreateStreamAppAclRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * createStreamAppAcl
     */
    createStreamAppAcl(requestParameters: CreateStreamAppAclRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary deleteAcl
     * @param {string} clusterName 
     * @param {KafkaAcl} kafkaAcl 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AclsApiInterface
     */
    deleteAclRaw(requestParameters: DeleteAclRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * deleteAcl
     */
    deleteAcl(requestParameters: DeleteAclRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary getAclAsCsv
     * @param {string} clusterName 
     * @param {KafkaAclResourceType} [resourceType] 
     * @param {string} [resourceName] 
     * @param {KafkaAclNamePatternType} [namePatternType] 
     * @param {string} [search] 
     * @param {boolean} [fts] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AclsApiInterface
     */
    getAclAsCsvRaw(requestParameters: GetAclAsCsvRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>>;

    /**
     * getAclAsCsv
     */
    getAclAsCsv(requestParameters: GetAclAsCsvRequest, initOverrides?: RequestInit): Promise<string>;

    /**
     * 
     * @summary listKafkaAcls
     * @param {string} clusterName 
     * @param {KafkaAclResourceType} [resourceType] 
     * @param {string} [resourceName] 
     * @param {KafkaAclNamePatternType} [namePatternType] 
     * @param {string} [search] 
     * @param {boolean} [fts] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AclsApiInterface
     */
    listAclsRaw(requestParameters: ListAclsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<KafkaAcl>>>;

    /**
     * listKafkaAcls
     */
    listAcls(requestParameters: ListAclsRequest, initOverrides?: RequestInit): Promise<Array<KafkaAcl>>;

    /**
     * 
     * @summary syncAclsCsv
     * @param {string} clusterName 
     * @param {string} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AclsApiInterface
     */
    syncAclsCsvRaw(requestParameters: SyncAclsCsvRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * syncAclsCsv
     */
    syncAclsCsv(requestParameters: SyncAclsCsvRequest, initOverrides?: RequestInit): Promise<void>;

}

/**
 * 
 */
export class AclsApi extends runtime.BaseAPI implements AclsApiInterface {

    /**
     * createAcl
     */
    async createAclRaw(requestParameters: CreateAclRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling createAcl.');
        }

        if (requestParameters.kafkaAcl === null || requestParameters.kafkaAcl === undefined) {
            throw new runtime.RequiredError('kafkaAcl','Required parameter requestParameters.kafkaAcl was null or undefined when calling createAcl.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/acls`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KafkaAclToJSON(requestParameters.kafkaAcl),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * createAcl
     */
    async createAcl(requestParameters: CreateAclRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createAclRaw(requestParameters, initOverrides);
    }

    /**
     * createConsumerAcl
     */
    async createConsumerAclRaw(requestParameters: CreateConsumerAclRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling createConsumerAcl.');
        }

        if (requestParameters.createConsumerAcl === null || requestParameters.createConsumerAcl === undefined) {
            throw new runtime.RequiredError('createConsumerAcl','Required parameter requestParameters.createConsumerAcl was null or undefined when calling createConsumerAcl.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/acls/consumer`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateConsumerAclToJSON(requestParameters.createConsumerAcl),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * createConsumerAcl
     */
    async createConsumerAcl(requestParameters: CreateConsumerAclRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createConsumerAclRaw(requestParameters, initOverrides);
    }

    /**
     * createProducerAcl
     */
    async createProducerAclRaw(requestParameters: CreateProducerAclRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling createProducerAcl.');
        }

        if (requestParameters.createProducerAcl === null || requestParameters.createProducerAcl === undefined) {
            throw new runtime.RequiredError('createProducerAcl','Required parameter requestParameters.createProducerAcl was null or undefined when calling createProducerAcl.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/acls/producer`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProducerAclToJSON(requestParameters.createProducerAcl),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * createProducerAcl
     */
    async createProducerAcl(requestParameters: CreateProducerAclRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createProducerAclRaw(requestParameters, initOverrides);
    }

    /**
     * createStreamAppAcl
     */
    async createStreamAppAclRaw(requestParameters: CreateStreamAppAclRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling createStreamAppAcl.');
        }

        if (requestParameters.createStreamAppAcl === null || requestParameters.createStreamAppAcl === undefined) {
            throw new runtime.RequiredError('createStreamAppAcl','Required parameter requestParameters.createStreamAppAcl was null or undefined when calling createStreamAppAcl.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/acls/streamapp`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateStreamAppAclToJSON(requestParameters.createStreamAppAcl),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * createStreamAppAcl
     */
    async createStreamAppAcl(requestParameters: CreateStreamAppAclRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createStreamAppAclRaw(requestParameters, initOverrides);
    }

    /**
     * deleteAcl
     */
    async deleteAclRaw(requestParameters: DeleteAclRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling deleteAcl.');
        }

        if (requestParameters.kafkaAcl === null || requestParameters.kafkaAcl === undefined) {
            throw new runtime.RequiredError('kafkaAcl','Required parameter requestParameters.kafkaAcl was null or undefined when calling deleteAcl.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/acls`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: KafkaAclToJSON(requestParameters.kafkaAcl),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * deleteAcl
     */
    async deleteAcl(requestParameters: DeleteAclRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteAclRaw(requestParameters, initOverrides);
    }

    /**
     * getAclAsCsv
     */
    async getAclAsCsvRaw(requestParameters: GetAclAsCsvRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getAclAsCsv.');
        }

        const queryParameters: any = {};

        if (requestParameters.resourceType !== undefined) {
            queryParameters['resourceType'] = requestParameters.resourceType;
        }

        if (requestParameters.resourceName !== undefined) {
            queryParameters['resourceName'] = requestParameters.resourceName;
        }

        if (requestParameters.namePatternType !== undefined) {
            queryParameters['namePatternType'] = requestParameters.namePatternType;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        if (requestParameters.fts !== undefined) {
            queryParameters['fts'] = requestParameters.fts;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/acls/csv`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * getAclAsCsv
     */
    async getAclAsCsv(requestParameters: GetAclAsCsvRequest, initOverrides?: RequestInit): Promise<string> {
        const response = await this.getAclAsCsvRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * listKafkaAcls
     */
    async listAclsRaw(requestParameters: ListAclsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<KafkaAcl>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling listAcls.');
        }

        const queryParameters: any = {};

        if (requestParameters.resourceType !== undefined) {
            queryParameters['resourceType'] = requestParameters.resourceType;
        }

        if (requestParameters.resourceName !== undefined) {
            queryParameters['resourceName'] = requestParameters.resourceName;
        }

        if (requestParameters.namePatternType !== undefined) {
            queryParameters['namePatternType'] = requestParameters.namePatternType;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        if (requestParameters.fts !== undefined) {
            queryParameters['fts'] = requestParameters.fts;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/acls`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(KafkaAclFromJSON));
    }

    /**
     * listKafkaAcls
     */
    async listAcls(requestParameters: ListAclsRequest, initOverrides?: RequestInit): Promise<Array<KafkaAcl>> {
        const response = await this.listAclsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * syncAclsCsv
     */
    async syncAclsCsvRaw(requestParameters: SyncAclsCsvRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling syncAclsCsv.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling syncAclsCsv.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/acls/csv`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * syncAclsCsv
     */
    async syncAclsCsv(requestParameters: SyncAclsCsvRequest, initOverrides?: RequestInit): Promise<void> {
        await this.syncAclsCsvRaw(requestParameters, initOverrides);
    }

}
