/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AuthenticationInfo,
    AuthenticationInfoFromJSON,
    AuthenticationInfoToJSON,
} from '../models';

/**
 * AuthorizationApi - interface
 * 
 * @export
 * @interface AuthorizationApiInterface
 */
export interface AuthorizationApiInterface {
    /**
     * 
     * @summary Get user authorization related info
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorizationApiInterface
     */
    getUserAuthInfoRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<AuthenticationInfo>>;

    /**
     * Get user authorization related info
     */
    getUserAuthInfo(initOverrides?: RequestInit): Promise<AuthenticationInfo>;

}

/**
 * 
 */
export class AuthorizationApi extends runtime.BaseAPI implements AuthorizationApiInterface {

    /**
     * Get user authorization related info
     */
    async getUserAuthInfoRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<AuthenticationInfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/authorization`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticationInfoFromJSON(jsonValue));
    }

    /**
     * Get user authorization related info
     */
    async getUserAuthInfo(initOverrides?: RequestInit): Promise<AuthenticationInfo> {
        const response = await this.getUserAuthInfoRaw(initOverrides);
        return await response.value();
    }

}
