/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ClientQuotas,
    ClientQuotasFromJSON,
    ClientQuotasToJSON,
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models';

export interface ListQuotasRequest {
    clusterName: string;
}

export interface UpsertClientQuotasRequest {
    clusterName: string;
    clientQuotas: ClientQuotas;
}

/**
 * ClientQuotasApi - interface
 * 
 * @export
 * @interface ClientQuotasApiInterface
 */
export interface ClientQuotasApiInterface {
    /**
     * 
     * @summary listQuotas
     * @param {string} clusterName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClientQuotasApiInterface
     */
    listQuotasRaw(requestParameters: ListQuotasRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ClientQuotas>>>;

    /**
     * listQuotas
     */
    listQuotas(requestParameters: ListQuotasRequest, initOverrides?: RequestInit): Promise<Array<ClientQuotas>>;

    /**
     * 
     * @summary upsertClientQuotas
     * @param {string} clusterName 
     * @param {ClientQuotas} clientQuotas 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClientQuotasApiInterface
     */
    upsertClientQuotasRaw(requestParameters: UpsertClientQuotasRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * upsertClientQuotas
     */
    upsertClientQuotas(requestParameters: UpsertClientQuotasRequest, initOverrides?: RequestInit): Promise<void>;

}

/**
 * 
 */
export class ClientQuotasApi extends runtime.BaseAPI implements ClientQuotasApiInterface {

    /**
     * listQuotas
     */
    async listQuotasRaw(requestParameters: ListQuotasRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ClientQuotas>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling listQuotas.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/clientquotas`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ClientQuotasFromJSON));
    }

    /**
     * listQuotas
     */
    async listQuotas(requestParameters: ListQuotasRequest, initOverrides?: RequestInit): Promise<Array<ClientQuotas>> {
        const response = await this.listQuotasRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * upsertClientQuotas
     */
    async upsertClientQuotasRaw(requestParameters: UpsertClientQuotasRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling upsertClientQuotas.');
        }

        if (requestParameters.clientQuotas === null || requestParameters.clientQuotas === undefined) {
            throw new runtime.RequiredError('clientQuotas','Required parameter requestParameters.clientQuotas was null or undefined when calling upsertClientQuotas.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/clientquotas`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ClientQuotasToJSON(requestParameters.clientQuotas),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * upsertClientQuotas
     */
    async upsertClientQuotas(requestParameters: UpsertClientQuotasRequest, initOverrides?: RequestInit): Promise<void> {
        await this.upsertClientQuotasRaw(requestParameters, initOverrides);
    }

}
