/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ConsumerGroup,
    ConsumerGroupFromJSON,
    ConsumerGroupToJSON,
    ConsumerGroupDetails,
    ConsumerGroupDetailsFromJSON,
    ConsumerGroupDetailsToJSON,
    ConsumerGroupOffsetsReset,
    ConsumerGroupOffsetsResetFromJSON,
    ConsumerGroupOffsetsResetToJSON,
    ConsumerGroupOrdering,
    ConsumerGroupOrderingFromJSON,
    ConsumerGroupOrderingToJSON,
    ConsumerGroupState,
    ConsumerGroupStateFromJSON,
    ConsumerGroupStateToJSON,
    ConsumerGroupsLagResponse,
    ConsumerGroupsLagResponseFromJSON,
    ConsumerGroupsLagResponseToJSON,
    ConsumerGroupsPageResponse,
    ConsumerGroupsPageResponseFromJSON,
    ConsumerGroupsPageResponseToJSON,
    SortOrder,
    SortOrderFromJSON,
    SortOrderToJSON,
} from '../models';

export interface DeleteConsumerGroupRequest {
    clusterName: string;
    id: string;
}

export interface DeleteConsumerGroupOffsetsRequest {
    clusterName: string;
    id: string;
    topicName: string;
}

export interface GetConsumerGroupRequest {
    clusterName: string;
    id: string;
}

export interface GetConsumerGroupsCsvRequest {
    clusterName: string;
    page?: number;
    perPage?: number;
    search?: string;
    orderBy?: ConsumerGroupOrdering;
    sortOrder?: SortOrder;
    fts?: boolean;
    state?: Array<ConsumerGroupState>;
}

export interface GetConsumerGroupsLagRequest {
    clusterName: string;
    ids: Array<string>;
    lastUpdate?: number;
    includePartitions?: boolean;
}

export interface GetConsumerGroupsPageRequest {
    clusterName: string;
    page?: number;
    perPage?: number;
    search?: string;
    orderBy?: ConsumerGroupOrdering;
    sortOrder?: SortOrder;
    fts?: boolean;
    state?: Array<ConsumerGroupState>;
}

export interface GetTopicConsumerGroupsRequest {
    clusterName: string;
    topicName: string;
}

export interface ResetConsumerGroupOffsetsRequest {
    clusterName: string;
    id: string;
    consumerGroupOffsetsReset: ConsumerGroupOffsetsReset;
}

/**
 * ConsumerGroupsApi - interface
 * 
 * @export
 * @interface ConsumerGroupsApiInterface
 */
export interface ConsumerGroupsApiInterface {
    /**
     * 
     * @summary deleteConsumerGroup
     * @param {string} clusterName 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConsumerGroupsApiInterface
     */
    deleteConsumerGroupRaw(requestParameters: DeleteConsumerGroupRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * deleteConsumerGroup
     */
    deleteConsumerGroup(requestParameters: DeleteConsumerGroupRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary deleteConsumerGroupOffsets
     * @param {string} clusterName 
     * @param {string} id 
     * @param {string} topicName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConsumerGroupsApiInterface
     */
    deleteConsumerGroupOffsetsRaw(requestParameters: DeleteConsumerGroupOffsetsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * deleteConsumerGroupOffsets
     */
    deleteConsumerGroupOffsets(requestParameters: DeleteConsumerGroupOffsetsRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary getConsumerGroup
     * @param {string} clusterName 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConsumerGroupsApiInterface
     */
    getConsumerGroupRaw(requestParameters: GetConsumerGroupRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ConsumerGroupDetails>>;

    /**
     * getConsumerGroup
     */
    getConsumerGroup(requestParameters: GetConsumerGroupRequest, initOverrides?: RequestInit): Promise<ConsumerGroupDetails>;

    /**
     * 
     * @summary getConsumerGroupsPage
     * @param {string} clusterName 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {string} [search] 
     * @param {ConsumerGroupOrdering} [orderBy] 
     * @param {SortOrder} [sortOrder] 
     * @param {boolean} [fts] 
     * @param {Array<ConsumerGroupState>} [state] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConsumerGroupsApiInterface
     */
    getConsumerGroupsCsvRaw(requestParameters: GetConsumerGroupsCsvRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>>;

    /**
     * getConsumerGroupsPage
     */
    getConsumerGroupsCsv(requestParameters: GetConsumerGroupsCsvRequest, initOverrides?: RequestInit): Promise<string>;

    /**
     * 
     * @summary getConsumerGroupsLag
     * @param {string} clusterName 
     * @param {Array<string>} ids 
     * @param {number} [lastUpdate] 
     * @param {boolean} [includePartitions] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConsumerGroupsApiInterface
     */
    getConsumerGroupsLagRaw(requestParameters: GetConsumerGroupsLagRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ConsumerGroupsLagResponse>>;

    /**
     * getConsumerGroupsLag
     */
    getConsumerGroupsLag(requestParameters: GetConsumerGroupsLagRequest, initOverrides?: RequestInit): Promise<ConsumerGroupsLagResponse>;

    /**
     * 
     * @summary getConsumerGroupsPage
     * @param {string} clusterName 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {string} [search] 
     * @param {ConsumerGroupOrdering} [orderBy] 
     * @param {SortOrder} [sortOrder] 
     * @param {boolean} [fts] 
     * @param {Array<ConsumerGroupState>} [state] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConsumerGroupsApiInterface
     */
    getConsumerGroupsPageRaw(requestParameters: GetConsumerGroupsPageRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ConsumerGroupsPageResponse>>;

    /**
     * getConsumerGroupsPage
     */
    getConsumerGroupsPage(requestParameters: GetConsumerGroupsPageRequest, initOverrides?: RequestInit): Promise<ConsumerGroupsPageResponse>;

    /**
     * 
     * @summary getTopicConsumerGroups
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConsumerGroupsApiInterface
     */
    getTopicConsumerGroupsRaw(requestParameters: GetTopicConsumerGroupsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ConsumerGroup>>>;

    /**
     * getTopicConsumerGroups
     */
    getTopicConsumerGroups(requestParameters: GetTopicConsumerGroupsRequest, initOverrides?: RequestInit): Promise<Array<ConsumerGroup>>;

    /**
     * 
     * @summary resetConsumerGroupOffsets
     * @param {string} clusterName 
     * @param {string} id 
     * @param {ConsumerGroupOffsetsReset} consumerGroupOffsetsReset 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConsumerGroupsApiInterface
     */
    resetConsumerGroupOffsetsRaw(requestParameters: ResetConsumerGroupOffsetsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * resetConsumerGroupOffsets
     */
    resetConsumerGroupOffsets(requestParameters: ResetConsumerGroupOffsetsRequest, initOverrides?: RequestInit): Promise<void>;

}

/**
 * 
 */
export class ConsumerGroupsApi extends runtime.BaseAPI implements ConsumerGroupsApiInterface {

    /**
     * deleteConsumerGroup
     */
    async deleteConsumerGroupRaw(requestParameters: DeleteConsumerGroupRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling deleteConsumerGroup.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteConsumerGroup.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/consumer-groups/{id}`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * deleteConsumerGroup
     */
    async deleteConsumerGroup(requestParameters: DeleteConsumerGroupRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteConsumerGroupRaw(requestParameters, initOverrides);
    }

    /**
     * deleteConsumerGroupOffsets
     */
    async deleteConsumerGroupOffsetsRaw(requestParameters: DeleteConsumerGroupOffsetsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling deleteConsumerGroupOffsets.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteConsumerGroupOffsets.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling deleteConsumerGroupOffsets.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/consumer-groups/{id}/topics/{topicName}`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * deleteConsumerGroupOffsets
     */
    async deleteConsumerGroupOffsets(requestParameters: DeleteConsumerGroupOffsetsRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteConsumerGroupOffsetsRaw(requestParameters, initOverrides);
    }

    /**
     * getConsumerGroup
     */
    async getConsumerGroupRaw(requestParameters: GetConsumerGroupRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ConsumerGroupDetails>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getConsumerGroup.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getConsumerGroup.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/consumer-groups/{id}`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsumerGroupDetailsFromJSON(jsonValue));
    }

    /**
     * getConsumerGroup
     */
    async getConsumerGroup(requestParameters: GetConsumerGroupRequest, initOverrides?: RequestInit): Promise<ConsumerGroupDetails> {
        const response = await this.getConsumerGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getConsumerGroupsPage
     */
    async getConsumerGroupsCsvRaw(requestParameters: GetConsumerGroupsCsvRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getConsumerGroupsCsv.');
        }

        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['perPage'] = requestParameters.perPage;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        if (requestParameters.orderBy !== undefined) {
            queryParameters['orderBy'] = requestParameters.orderBy;
        }

        if (requestParameters.sortOrder !== undefined) {
            queryParameters['sortOrder'] = requestParameters.sortOrder;
        }

        if (requestParameters.fts !== undefined) {
            queryParameters['fts'] = requestParameters.fts;
        }

        if (requestParameters.state) {
            queryParameters['state'] = requestParameters.state.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/consumer-groups/csv`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * getConsumerGroupsPage
     */
    async getConsumerGroupsCsv(requestParameters: GetConsumerGroupsCsvRequest, initOverrides?: RequestInit): Promise<string> {
        const response = await this.getConsumerGroupsCsvRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getConsumerGroupsLag
     */
    async getConsumerGroupsLagRaw(requestParameters: GetConsumerGroupsLagRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ConsumerGroupsLagResponse>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getConsumerGroupsLag.');
        }

        if (requestParameters.ids === null || requestParameters.ids === undefined) {
            throw new runtime.RequiredError('ids','Required parameter requestParameters.ids was null or undefined when calling getConsumerGroupsLag.');
        }

        const queryParameters: any = {};

        if (requestParameters.ids) {
            queryParameters['ids'] = requestParameters.ids.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.lastUpdate !== undefined) {
            queryParameters['lastUpdate'] = requestParameters.lastUpdate;
        }

        if (requestParameters.includePartitions !== undefined) {
            queryParameters['includePartitions'] = requestParameters.includePartitions;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/consumer-groups/lag`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsumerGroupsLagResponseFromJSON(jsonValue));
    }

    /**
     * getConsumerGroupsLag
     */
    async getConsumerGroupsLag(requestParameters: GetConsumerGroupsLagRequest, initOverrides?: RequestInit): Promise<ConsumerGroupsLagResponse> {
        const response = await this.getConsumerGroupsLagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getConsumerGroupsPage
     */
    async getConsumerGroupsPageRaw(requestParameters: GetConsumerGroupsPageRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ConsumerGroupsPageResponse>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getConsumerGroupsPage.');
        }

        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['perPage'] = requestParameters.perPage;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        if (requestParameters.orderBy !== undefined) {
            queryParameters['orderBy'] = requestParameters.orderBy;
        }

        if (requestParameters.sortOrder !== undefined) {
            queryParameters['sortOrder'] = requestParameters.sortOrder;
        }

        if (requestParameters.fts !== undefined) {
            queryParameters['fts'] = requestParameters.fts;
        }

        if (requestParameters.state) {
            queryParameters['state'] = requestParameters.state.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/consumer-groups/paged`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsumerGroupsPageResponseFromJSON(jsonValue));
    }

    /**
     * getConsumerGroupsPage
     */
    async getConsumerGroupsPage(requestParameters: GetConsumerGroupsPageRequest, initOverrides?: RequestInit): Promise<ConsumerGroupsPageResponse> {
        const response = await this.getConsumerGroupsPageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getTopicConsumerGroups
     */
    async getTopicConsumerGroupsRaw(requestParameters: GetTopicConsumerGroupsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ConsumerGroup>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getTopicConsumerGroups.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling getTopicConsumerGroups.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/consumer-groups`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ConsumerGroupFromJSON));
    }

    /**
     * getTopicConsumerGroups
     */
    async getTopicConsumerGroups(requestParameters: GetTopicConsumerGroupsRequest, initOverrides?: RequestInit): Promise<Array<ConsumerGroup>> {
        const response = await this.getTopicConsumerGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * resetConsumerGroupOffsets
     */
    async resetConsumerGroupOffsetsRaw(requestParameters: ResetConsumerGroupOffsetsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling resetConsumerGroupOffsets.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling resetConsumerGroupOffsets.');
        }

        if (requestParameters.consumerGroupOffsetsReset === null || requestParameters.consumerGroupOffsetsReset === undefined) {
            throw new runtime.RequiredError('consumerGroupOffsetsReset','Required parameter requestParameters.consumerGroupOffsetsReset was null or undefined when calling resetConsumerGroupOffsets.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/consumer-groups/{id}/offsets`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConsumerGroupOffsetsResetToJSON(requestParameters.consumerGroupOffsetsReset),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * resetConsumerGroupOffsets
     */
    async resetConsumerGroupOffsets(requestParameters: ResetConsumerGroupOffsetsRequest, initOverrides?: RequestInit): Promise<void> {
        await this.resetConsumerGroupOffsetsRaw(requestParameters, initOverrides);
    }

}
