/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    GraphDataRequest,
    GraphDataRequestFromJSON,
    GraphDataRequestToJSON,
    GraphDescriptions,
    GraphDescriptionsFromJSON,
    GraphDescriptionsToJSON,
    PrometheusApiQueryResponse,
    PrometheusApiQueryResponseFromJSON,
    PrometheusApiQueryResponseToJSON,
} from '../models';

export interface GetGraphDataRequest {
    clusterName: string;
    graphDataRequest: GraphDataRequest;
}

export interface GetGraphsListRequest {
    clusterName: string;
}

/**
 * GraphsApi - interface
 * 
 * @export
 * @interface GraphsApiInterface
 */
export interface GraphsApiInterface {
    /**
     * 
     * @summary getGraphData
     * @param {string} clusterName 
     * @param {GraphDataRequest} graphDataRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GraphsApiInterface
     */
    getGraphDataRaw(requestParameters: GetGraphDataRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<PrometheusApiQueryResponse>>;

    /**
     * getGraphData
     */
    getGraphData(requestParameters: GetGraphDataRequest, initOverrides?: RequestInit): Promise<PrometheusApiQueryResponse>;

    /**
     * 
     * @summary getGraphsList
     * @param {string} clusterName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GraphsApiInterface
     */
    getGraphsListRaw(requestParameters: GetGraphsListRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GraphDescriptions>>;

    /**
     * getGraphsList
     */
    getGraphsList(requestParameters: GetGraphsListRequest, initOverrides?: RequestInit): Promise<GraphDescriptions>;

}

/**
 * 
 */
export class GraphsApi extends runtime.BaseAPI implements GraphsApiInterface {

    /**
     * getGraphData
     */
    async getGraphDataRaw(requestParameters: GetGraphDataRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<PrometheusApiQueryResponse>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getGraphData.');
        }

        if (requestParameters.graphDataRequest === null || requestParameters.graphDataRequest === undefined) {
            throw new runtime.RequiredError('graphDataRequest','Required parameter requestParameters.graphDataRequest was null or undefined when calling getGraphData.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/graphs`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GraphDataRequestToJSON(requestParameters.graphDataRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PrometheusApiQueryResponseFromJSON(jsonValue));
    }

    /**
     * getGraphData
     */
    async getGraphData(requestParameters: GetGraphDataRequest, initOverrides?: RequestInit): Promise<PrometheusApiQueryResponse> {
        const response = await this.getGraphDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getGraphsList
     */
    async getGraphsListRaw(requestParameters: GetGraphsListRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GraphDescriptions>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getGraphsList.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/graphs`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GraphDescriptionsFromJSON(jsonValue));
    }

    /**
     * getGraphsList
     */
    async getGraphsList(requestParameters: GetGraphsListRequest, initOverrides?: RequestInit): Promise<GraphDescriptions> {
        const response = await this.getGraphsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
