/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ApiRebalanceInProgressResponse,
    ApiRebalanceInProgressResponseFromJSON,
    ApiRebalanceInProgressResponseToJSON,
    Connect,
    ConnectFromJSON,
    ConnectToJSON,
    Connector,
    ConnectorFromJSON,
    ConnectorToJSON,
    ConnectorAction,
    ConnectorActionFromJSON,
    ConnectorActionToJSON,
    ConnectorColumnsToSort,
    ConnectorColumnsToSortFromJSON,
    ConnectorColumnsToSortToJSON,
    ConnectorPlugin,
    ConnectorPluginFromJSON,
    ConnectorPluginToJSON,
    ConnectorPluginConfigValidationResponse,
    ConnectorPluginConfigValidationResponseFromJSON,
    ConnectorPluginConfigValidationResponseToJSON,
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    FullConnectorInfo,
    FullConnectorInfoFromJSON,
    FullConnectorInfoToJSON,
    NewConnector,
    NewConnectorFromJSON,
    NewConnectorToJSON,
    SortOrder,
    SortOrderFromJSON,
    SortOrderToJSON,
    Task,
    TaskFromJSON,
    TaskToJSON,
} from '../models';

export interface CreateConnectorRequest {
    clusterName: string;
    connectName: string;
    newConnector: NewConnector;
}

export interface DeleteConnectorRequest {
    clusterName: string;
    connectName: string;
    connectorName: string;
}

export interface GetAllConnectorsRequest {
    clusterName: string;
    search?: string;
    orderBy?: ConnectorColumnsToSort;
    sortOrder?: SortOrder;
    fts?: boolean;
}

export interface GetAllConnectorsCsvRequest {
    clusterName: string;
    search?: string;
    orderBy?: ConnectorColumnsToSort;
    sortOrder?: SortOrder;
    fts?: boolean;
}

export interface GetConnectorRequest {
    clusterName: string;
    connectName: string;
    connectorName: string;
}

export interface GetConnectorConfigRequest {
    clusterName: string;
    connectName: string;
    connectorName: string;
}

export interface GetConnectorPluginsRequest {
    clusterName: string;
    connectName: string;
}

export interface GetConnectorTasksRequest {
    clusterName: string;
    connectName: string;
    connectorName: string;
}

export interface GetConnectorsRequest {
    clusterName: string;
    connectName: string;
}

export interface GetConnectsRequest {
    clusterName: string;
    withStats?: boolean;
}

export interface GetConnectsCsvRequest {
    clusterName: string;
    withStats?: boolean;
}

export interface ResetConnectorOffsetsRequest {
    clusterName: string;
    connectName: string;
    connectorName: string;
}

export interface RestartConnectorTaskRequest {
    clusterName: string;
    connectName: string;
    connectorName: string;
    taskId: number;
}

export interface SetConnectorConfigRequest {
    clusterName: string;
    connectName: string;
    connectorName: string;
    requestBody: { [key: string]: any | undefined; };
}

export interface UpdateConnectorStateRequest {
    clusterName: string;
    connectName: string;
    connectorName: string;
    action: ConnectorAction;
}

export interface ValidateConnectorPluginConfigRequest {
    clusterName: string;
    connectName: string;
    pluginName: string;
    requestBody: { [key: string]: any | undefined; };
}

/**
 * KafkaConnectApi - interface
 * 
 * @export
 * @interface KafkaConnectApiInterface
 */
export interface KafkaConnectApiInterface {
    /**
     * 
     * @summary createConnector
     * @param {string} clusterName 
     * @param {string} connectName 
     * @param {NewConnector} newConnector 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    createConnectorRaw(requestParameters: CreateConnectorRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Connector>>;

    /**
     * createConnector
     */
    createConnector(requestParameters: CreateConnectorRequest, initOverrides?: RequestInit): Promise<Connector>;

    /**
     * 
     * @summary deleteConnector
     * @param {string} clusterName 
     * @param {string} connectName 
     * @param {string} connectorName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    deleteConnectorRaw(requestParameters: DeleteConnectorRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * deleteConnector
     */
    deleteConnector(requestParameters: DeleteConnectorRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary getAllConnectors
     * @param {string} clusterName 
     * @param {string} [search] 
     * @param {ConnectorColumnsToSort} [orderBy] 
     * @param {SortOrder} [sortOrder] 
     * @param {boolean} [fts] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    getAllConnectorsRaw(requestParameters: GetAllConnectorsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<FullConnectorInfo>>>;

    /**
     * getAllConnectors
     */
    getAllConnectors(requestParameters: GetAllConnectorsRequest, initOverrides?: RequestInit): Promise<Array<FullConnectorInfo>>;

    /**
     * 
     * @summary getAllConnectorsCsv
     * @param {string} clusterName 
     * @param {string} [search] 
     * @param {ConnectorColumnsToSort} [orderBy] 
     * @param {SortOrder} [sortOrder] 
     * @param {boolean} [fts] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    getAllConnectorsCsvRaw(requestParameters: GetAllConnectorsCsvRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>>;

    /**
     * getAllConnectorsCsv
     */
    getAllConnectorsCsv(requestParameters: GetAllConnectorsCsvRequest, initOverrides?: RequestInit): Promise<string>;

    /**
     * 
     * @summary getConnector
     * @param {string} clusterName 
     * @param {string} connectName 
     * @param {string} connectorName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    getConnectorRaw(requestParameters: GetConnectorRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Connector>>;

    /**
     * getConnector
     */
    getConnector(requestParameters: GetConnectorRequest, initOverrides?: RequestInit): Promise<Connector>;

    /**
     * 
     * @summary getConnectorConfig
     * @param {string} clusterName 
     * @param {string} connectName 
     * @param {string} connectorName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    getConnectorConfigRaw(requestParameters: GetConnectorConfigRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<{ [key: string]: any | undefined; }>>;

    /**
     * getConnectorConfig
     */
    getConnectorConfig(requestParameters: GetConnectorConfigRequest, initOverrides?: RequestInit): Promise<{ [key: string]: any | undefined; }>;

    /**
     * 
     * @summary get connector plugins
     * @param {string} clusterName 
     * @param {string} connectName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    getConnectorPluginsRaw(requestParameters: GetConnectorPluginsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ConnectorPlugin>>>;

    /**
     * get connector plugins
     */
    getConnectorPlugins(requestParameters: GetConnectorPluginsRequest, initOverrides?: RequestInit): Promise<Array<ConnectorPlugin>>;

    /**
     * 
     * @summary getConnectorTasks
     * @param {string} clusterName 
     * @param {string} connectName 
     * @param {string} connectorName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    getConnectorTasksRaw(requestParameters: GetConnectorTasksRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Task>>>;

    /**
     * getConnectorTasks
     */
    getConnectorTasks(requestParameters: GetConnectorTasksRequest, initOverrides?: RequestInit): Promise<Array<Task>>;

    /**
     * 
     * @summary getConnectors
     * @param {string} clusterName 
     * @param {string} connectName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    getConnectorsRaw(requestParameters: GetConnectorsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     * getConnectors
     */
    getConnectors(requestParameters: GetConnectorsRequest, initOverrides?: RequestInit): Promise<Array<string>>;

    /**
     * 
     * @summary getConnects
     * @param {string} clusterName 
     * @param {boolean} [withStats] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    getConnectsRaw(requestParameters: GetConnectsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Connect>>>;

    /**
     * getConnects
     */
    getConnects(requestParameters: GetConnectsRequest, initOverrides?: RequestInit): Promise<Array<Connect>>;

    /**
     * 
     * @summary getConnects
     * @param {string} clusterName 
     * @param {boolean} [withStats] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    getConnectsCsvRaw(requestParameters: GetConnectsCsvRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>>;

    /**
     * getConnects
     */
    getConnectsCsv(requestParameters: GetConnectsCsvRequest, initOverrides?: RequestInit): Promise<string>;

    /**
     * 
     * @summary resetConnectorOffsets
     * @param {string} clusterName 
     * @param {string} connectName 
     * @param {string} connectorName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    resetConnectorOffsetsRaw(requestParameters: ResetConnectorOffsetsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * resetConnectorOffsets
     */
    resetConnectorOffsets(requestParameters: ResetConnectorOffsetsRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary restartConnectorTask
     * @param {string} clusterName 
     * @param {string} connectName 
     * @param {string} connectorName 
     * @param {number} taskId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    restartConnectorTaskRaw(requestParameters: RestartConnectorTaskRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * restartConnectorTask
     */
    restartConnectorTask(requestParameters: RestartConnectorTaskRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary setConnectorConfig
     * @param {string} clusterName 
     * @param {string} connectName 
     * @param {string} connectorName 
     * @param {{ [key: string]: any | undefined; }} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    setConnectorConfigRaw(requestParameters: SetConnectorConfigRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Connector>>;

    /**
     * setConnectorConfig
     */
    setConnectorConfig(requestParameters: SetConnectorConfigRequest, initOverrides?: RequestInit): Promise<Connector>;

    /**
     * 
     * @summary updateConnectorState
     * @param {string} clusterName 
     * @param {string} connectName 
     * @param {string} connectorName 
     * @param {ConnectorAction} action 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    updateConnectorStateRaw(requestParameters: UpdateConnectorStateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * updateConnectorState
     */
    updateConnectorState(requestParameters: UpdateConnectorStateRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary validate connector plugin configuration
     * @param {string} clusterName 
     * @param {string} connectName 
     * @param {string} pluginName 
     * @param {{ [key: string]: any | undefined; }} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KafkaConnectApiInterface
     */
    validateConnectorPluginConfigRaw(requestParameters: ValidateConnectorPluginConfigRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ConnectorPluginConfigValidationResponse>>;

    /**
     * validate connector plugin configuration
     */
    validateConnectorPluginConfig(requestParameters: ValidateConnectorPluginConfigRequest, initOverrides?: RequestInit): Promise<ConnectorPluginConfigValidationResponse>;

}

/**
 * 
 */
export class KafkaConnectApi extends runtime.BaseAPI implements KafkaConnectApiInterface {

    /**
     * createConnector
     */
    async createConnectorRaw(requestParameters: CreateConnectorRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Connector>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling createConnector.');
        }

        if (requestParameters.connectName === null || requestParameters.connectName === undefined) {
            throw new runtime.RequiredError('connectName','Required parameter requestParameters.connectName was null or undefined when calling createConnector.');
        }

        if (requestParameters.newConnector === null || requestParameters.newConnector === undefined) {
            throw new runtime.RequiredError('newConnector','Required parameter requestParameters.newConnector was null or undefined when calling createConnector.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connects/{connectName}/connectors`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"connectName"}}`, encodeURIComponent(String(requestParameters.connectName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewConnectorToJSON(requestParameters.newConnector),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectorFromJSON(jsonValue));
    }

    /**
     * createConnector
     */
    async createConnector(requestParameters: CreateConnectorRequest, initOverrides?: RequestInit): Promise<Connector> {
        const response = await this.createConnectorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * deleteConnector
     */
    async deleteConnectorRaw(requestParameters: DeleteConnectorRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling deleteConnector.');
        }

        if (requestParameters.connectName === null || requestParameters.connectName === undefined) {
            throw new runtime.RequiredError('connectName','Required parameter requestParameters.connectName was null or undefined when calling deleteConnector.');
        }

        if (requestParameters.connectorName === null || requestParameters.connectorName === undefined) {
            throw new runtime.RequiredError('connectorName','Required parameter requestParameters.connectorName was null or undefined when calling deleteConnector.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connects/{connectName}/connectors/{connectorName}`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"connectName"}}`, encodeURIComponent(String(requestParameters.connectName))).replace(`{${"connectorName"}}`, encodeURIComponent(String(requestParameters.connectorName))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * deleteConnector
     */
    async deleteConnector(requestParameters: DeleteConnectorRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteConnectorRaw(requestParameters, initOverrides);
    }

    /**
     * getAllConnectors
     */
    async getAllConnectorsRaw(requestParameters: GetAllConnectorsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<FullConnectorInfo>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getAllConnectors.');
        }

        const queryParameters: any = {};

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        if (requestParameters.orderBy !== undefined) {
            queryParameters['orderBy'] = requestParameters.orderBy;
        }

        if (requestParameters.sortOrder !== undefined) {
            queryParameters['sortOrder'] = requestParameters.sortOrder;
        }

        if (requestParameters.fts !== undefined) {
            queryParameters['fts'] = requestParameters.fts;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connectors`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FullConnectorInfoFromJSON));
    }

    /**
     * getAllConnectors
     */
    async getAllConnectors(requestParameters: GetAllConnectorsRequest, initOverrides?: RequestInit): Promise<Array<FullConnectorInfo>> {
        const response = await this.getAllConnectorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getAllConnectorsCsv
     */
    async getAllConnectorsCsvRaw(requestParameters: GetAllConnectorsCsvRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getAllConnectorsCsv.');
        }

        const queryParameters: any = {};

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        if (requestParameters.orderBy !== undefined) {
            queryParameters['orderBy'] = requestParameters.orderBy;
        }

        if (requestParameters.sortOrder !== undefined) {
            queryParameters['sortOrder'] = requestParameters.sortOrder;
        }

        if (requestParameters.fts !== undefined) {
            queryParameters['fts'] = requestParameters.fts;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connectors/csv`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * getAllConnectorsCsv
     */
    async getAllConnectorsCsv(requestParameters: GetAllConnectorsCsvRequest, initOverrides?: RequestInit): Promise<string> {
        const response = await this.getAllConnectorsCsvRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getConnector
     */
    async getConnectorRaw(requestParameters: GetConnectorRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Connector>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getConnector.');
        }

        if (requestParameters.connectName === null || requestParameters.connectName === undefined) {
            throw new runtime.RequiredError('connectName','Required parameter requestParameters.connectName was null or undefined when calling getConnector.');
        }

        if (requestParameters.connectorName === null || requestParameters.connectorName === undefined) {
            throw new runtime.RequiredError('connectorName','Required parameter requestParameters.connectorName was null or undefined when calling getConnector.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connects/{connectName}/connectors/{connectorName}`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"connectName"}}`, encodeURIComponent(String(requestParameters.connectName))).replace(`{${"connectorName"}}`, encodeURIComponent(String(requestParameters.connectorName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectorFromJSON(jsonValue));
    }

    /**
     * getConnector
     */
    async getConnector(requestParameters: GetConnectorRequest, initOverrides?: RequestInit): Promise<Connector> {
        const response = await this.getConnectorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getConnectorConfig
     */
    async getConnectorConfigRaw(requestParameters: GetConnectorConfigRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<{ [key: string]: any | undefined; }>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getConnectorConfig.');
        }

        if (requestParameters.connectName === null || requestParameters.connectName === undefined) {
            throw new runtime.RequiredError('connectName','Required parameter requestParameters.connectName was null or undefined when calling getConnectorConfig.');
        }

        if (requestParameters.connectorName === null || requestParameters.connectorName === undefined) {
            throw new runtime.RequiredError('connectorName','Required parameter requestParameters.connectorName was null or undefined when calling getConnectorConfig.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connects/{connectName}/connectors/{connectorName}/config`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"connectName"}}`, encodeURIComponent(String(requestParameters.connectName))).replace(`{${"connectorName"}}`, encodeURIComponent(String(requestParameters.connectorName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * getConnectorConfig
     */
    async getConnectorConfig(requestParameters: GetConnectorConfigRequest, initOverrides?: RequestInit): Promise<{ [key: string]: any | undefined; }> {
        const response = await this.getConnectorConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get connector plugins
     */
    async getConnectorPluginsRaw(requestParameters: GetConnectorPluginsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ConnectorPlugin>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getConnectorPlugins.');
        }

        if (requestParameters.connectName === null || requestParameters.connectName === undefined) {
            throw new runtime.RequiredError('connectName','Required parameter requestParameters.connectName was null or undefined when calling getConnectorPlugins.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connects/{connectName}/plugins`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"connectName"}}`, encodeURIComponent(String(requestParameters.connectName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ConnectorPluginFromJSON));
    }

    /**
     * get connector plugins
     */
    async getConnectorPlugins(requestParameters: GetConnectorPluginsRequest, initOverrides?: RequestInit): Promise<Array<ConnectorPlugin>> {
        const response = await this.getConnectorPluginsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getConnectorTasks
     */
    async getConnectorTasksRaw(requestParameters: GetConnectorTasksRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Task>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getConnectorTasks.');
        }

        if (requestParameters.connectName === null || requestParameters.connectName === undefined) {
            throw new runtime.RequiredError('connectName','Required parameter requestParameters.connectName was null or undefined when calling getConnectorTasks.');
        }

        if (requestParameters.connectorName === null || requestParameters.connectorName === undefined) {
            throw new runtime.RequiredError('connectorName','Required parameter requestParameters.connectorName was null or undefined when calling getConnectorTasks.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connects/{connectName}/connectors/{connectorName}/tasks`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"connectName"}}`, encodeURIComponent(String(requestParameters.connectName))).replace(`{${"connectorName"}}`, encodeURIComponent(String(requestParameters.connectorName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskFromJSON));
    }

    /**
     * getConnectorTasks
     */
    async getConnectorTasks(requestParameters: GetConnectorTasksRequest, initOverrides?: RequestInit): Promise<Array<Task>> {
        const response = await this.getConnectorTasksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getConnectors
     */
    async getConnectorsRaw(requestParameters: GetConnectorsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getConnectors.');
        }

        if (requestParameters.connectName === null || requestParameters.connectName === undefined) {
            throw new runtime.RequiredError('connectName','Required parameter requestParameters.connectName was null or undefined when calling getConnectors.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connects/{connectName}/connectors`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"connectName"}}`, encodeURIComponent(String(requestParameters.connectName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * getConnectors
     */
    async getConnectors(requestParameters: GetConnectorsRequest, initOverrides?: RequestInit): Promise<Array<string>> {
        const response = await this.getConnectorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getConnects
     */
    async getConnectsRaw(requestParameters: GetConnectsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Connect>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getConnects.');
        }

        const queryParameters: any = {};

        if (requestParameters.withStats !== undefined) {
            queryParameters['withStats'] = requestParameters.withStats;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connects`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ConnectFromJSON));
    }

    /**
     * getConnects
     */
    async getConnects(requestParameters: GetConnectsRequest, initOverrides?: RequestInit): Promise<Array<Connect>> {
        const response = await this.getConnectsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getConnects
     */
    async getConnectsCsvRaw(requestParameters: GetConnectsCsvRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getConnectsCsv.');
        }

        const queryParameters: any = {};

        if (requestParameters.withStats !== undefined) {
            queryParameters['withStats'] = requestParameters.withStats;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connects/csv`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * getConnects
     */
    async getConnectsCsv(requestParameters: GetConnectsCsvRequest, initOverrides?: RequestInit): Promise<string> {
        const response = await this.getConnectsCsvRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * resetConnectorOffsets
     */
    async resetConnectorOffsetsRaw(requestParameters: ResetConnectorOffsetsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling resetConnectorOffsets.');
        }

        if (requestParameters.connectName === null || requestParameters.connectName === undefined) {
            throw new runtime.RequiredError('connectName','Required parameter requestParameters.connectName was null or undefined when calling resetConnectorOffsets.');
        }

        if (requestParameters.connectorName === null || requestParameters.connectorName === undefined) {
            throw new runtime.RequiredError('connectorName','Required parameter requestParameters.connectorName was null or undefined when calling resetConnectorOffsets.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connects/{connectName}/connectors/{connectorName}/offsets`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"connectName"}}`, encodeURIComponent(String(requestParameters.connectName))).replace(`{${"connectorName"}}`, encodeURIComponent(String(requestParameters.connectorName))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * resetConnectorOffsets
     */
    async resetConnectorOffsets(requestParameters: ResetConnectorOffsetsRequest, initOverrides?: RequestInit): Promise<void> {
        await this.resetConnectorOffsetsRaw(requestParameters, initOverrides);
    }

    /**
     * restartConnectorTask
     */
    async restartConnectorTaskRaw(requestParameters: RestartConnectorTaskRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling restartConnectorTask.');
        }

        if (requestParameters.connectName === null || requestParameters.connectName === undefined) {
            throw new runtime.RequiredError('connectName','Required parameter requestParameters.connectName was null or undefined when calling restartConnectorTask.');
        }

        if (requestParameters.connectorName === null || requestParameters.connectorName === undefined) {
            throw new runtime.RequiredError('connectorName','Required parameter requestParameters.connectorName was null or undefined when calling restartConnectorTask.');
        }

        if (requestParameters.taskId === null || requestParameters.taskId === undefined) {
            throw new runtime.RequiredError('taskId','Required parameter requestParameters.taskId was null or undefined when calling restartConnectorTask.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connects/{connectName}/connectors/{connectorName}/tasks/{taskId}/action/restart`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"connectName"}}`, encodeURIComponent(String(requestParameters.connectName))).replace(`{${"connectorName"}}`, encodeURIComponent(String(requestParameters.connectorName))).replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters.taskId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * restartConnectorTask
     */
    async restartConnectorTask(requestParameters: RestartConnectorTaskRequest, initOverrides?: RequestInit): Promise<void> {
        await this.restartConnectorTaskRaw(requestParameters, initOverrides);
    }

    /**
     * setConnectorConfig
     */
    async setConnectorConfigRaw(requestParameters: SetConnectorConfigRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Connector>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling setConnectorConfig.');
        }

        if (requestParameters.connectName === null || requestParameters.connectName === undefined) {
            throw new runtime.RequiredError('connectName','Required parameter requestParameters.connectName was null or undefined when calling setConnectorConfig.');
        }

        if (requestParameters.connectorName === null || requestParameters.connectorName === undefined) {
            throw new runtime.RequiredError('connectorName','Required parameter requestParameters.connectorName was null or undefined when calling setConnectorConfig.');
        }

        if (requestParameters.requestBody === null || requestParameters.requestBody === undefined) {
            throw new runtime.RequiredError('requestBody','Required parameter requestParameters.requestBody was null or undefined when calling setConnectorConfig.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connects/{connectName}/connectors/{connectorName}/config`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"connectName"}}`, encodeURIComponent(String(requestParameters.connectName))).replace(`{${"connectorName"}}`, encodeURIComponent(String(requestParameters.connectorName))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.requestBody,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectorFromJSON(jsonValue));
    }

    /**
     * setConnectorConfig
     */
    async setConnectorConfig(requestParameters: SetConnectorConfigRequest, initOverrides?: RequestInit): Promise<Connector> {
        const response = await this.setConnectorConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * updateConnectorState
     */
    async updateConnectorStateRaw(requestParameters: UpdateConnectorStateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling updateConnectorState.');
        }

        if (requestParameters.connectName === null || requestParameters.connectName === undefined) {
            throw new runtime.RequiredError('connectName','Required parameter requestParameters.connectName was null or undefined when calling updateConnectorState.');
        }

        if (requestParameters.connectorName === null || requestParameters.connectorName === undefined) {
            throw new runtime.RequiredError('connectorName','Required parameter requestParameters.connectorName was null or undefined when calling updateConnectorState.');
        }

        if (requestParameters.action === null || requestParameters.action === undefined) {
            throw new runtime.RequiredError('action','Required parameter requestParameters.action was null or undefined when calling updateConnectorState.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connects/{connectName}/connectors/{connectorName}/action/{action}`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"connectName"}}`, encodeURIComponent(String(requestParameters.connectName))).replace(`{${"connectorName"}}`, encodeURIComponent(String(requestParameters.connectorName))).replace(`{${"action"}}`, encodeURIComponent(String(requestParameters.action))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * updateConnectorState
     */
    async updateConnectorState(requestParameters: UpdateConnectorStateRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateConnectorStateRaw(requestParameters, initOverrides);
    }

    /**
     * validate connector plugin configuration
     */
    async validateConnectorPluginConfigRaw(requestParameters: ValidateConnectorPluginConfigRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ConnectorPluginConfigValidationResponse>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling validateConnectorPluginConfig.');
        }

        if (requestParameters.connectName === null || requestParameters.connectName === undefined) {
            throw new runtime.RequiredError('connectName','Required parameter requestParameters.connectName was null or undefined when calling validateConnectorPluginConfig.');
        }

        if (requestParameters.pluginName === null || requestParameters.pluginName === undefined) {
            throw new runtime.RequiredError('pluginName','Required parameter requestParameters.pluginName was null or undefined when calling validateConnectorPluginConfig.');
        }

        if (requestParameters.requestBody === null || requestParameters.requestBody === undefined) {
            throw new runtime.RequiredError('requestBody','Required parameter requestParameters.requestBody was null or undefined when calling validateConnectorPluginConfig.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/connects/{connectName}/plugins/{pluginName}/config/validate`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"connectName"}}`, encodeURIComponent(String(requestParameters.connectName))).replace(`{${"pluginName"}}`, encodeURIComponent(String(requestParameters.pluginName))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.requestBody,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectorPluginConfigValidationResponseFromJSON(jsonValue));
    }

    /**
     * validate connector plugin configuration
     */
    async validateConnectorPluginConfig(requestParameters: ValidateConnectorPluginConfigRequest, initOverrides?: RequestInit): Promise<ConnectorPluginConfigValidationResponse> {
        const response = await this.validateConnectorPluginConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
