/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    KsqlCommandV2,
    KsqlCommandV2FromJSON,
    KsqlCommandV2ToJSON,
    KsqlCommandV2Response,
    KsqlCommandV2ResponseFromJSON,
    KsqlCommandV2ResponseToJSON,
    KsqlResponse,
    KsqlResponseFromJSON,
    KsqlResponseToJSON,
    KsqlStreamDescription,
    KsqlStreamDescriptionFromJSON,
    KsqlStreamDescriptionToJSON,
    KsqlTableDescription,
    KsqlTableDescriptionFromJSON,
    KsqlTableDescriptionToJSON,
} from '../models';

export interface ExecuteKsqlRequest {
    clusterName: string;
    ksqlCommandV2: KsqlCommandV2;
}

export interface ListStreamsRequest {
    clusterName: string;
}

export interface ListTablesRequest {
    clusterName: string;
}

export interface OpenKsqlResponsePipeRequest {
    clusterName: string;
    pipeId: string;
}

/**
 * KsqlApi - interface
 * 
 * @export
 * @interface KsqlApiInterface
 */
export interface KsqlApiInterface {
    /**
     * 
     * @summary executeKsql
     * @param {string} clusterName 
     * @param {KsqlCommandV2} ksqlCommandV2 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KsqlApiInterface
     */
    executeKsqlRaw(requestParameters: ExecuteKsqlRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<KsqlCommandV2Response>>;

    /**
     * executeKsql
     */
    executeKsql(requestParameters: ExecuteKsqlRequest, initOverrides?: RequestInit): Promise<KsqlCommandV2Response>;

    /**
     * 
     * @summary listStreams
     * @param {string} clusterName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KsqlApiInterface
     */
    listStreamsRaw(requestParameters: ListStreamsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<KsqlStreamDescription>>>;

    /**
     * listStreams
     */
    listStreams(requestParameters: ListStreamsRequest, initOverrides?: RequestInit): Promise<Array<KsqlStreamDescription>>;

    /**
     * 
     * @summary listTables
     * @param {string} clusterName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KsqlApiInterface
     */
    listTablesRaw(requestParameters: ListTablesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<KsqlTableDescription>>>;

    /**
     * listTables
     */
    listTables(requestParameters: ListTablesRequest, initOverrides?: RequestInit): Promise<Array<KsqlTableDescription>>;

    /**
     * 
     * @summary openKsqlResponsePipe
     * @param {string} clusterName 
     * @param {string} pipeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KsqlApiInterface
     */
    openKsqlResponsePipeRaw(requestParameters: OpenKsqlResponsePipeRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<KsqlResponse>>>;

    /**
     * openKsqlResponsePipe
     */
    openKsqlResponsePipe(requestParameters: OpenKsqlResponsePipeRequest, initOverrides?: RequestInit): Promise<Array<KsqlResponse>>;

}

/**
 * 
 */
export class KsqlApi extends runtime.BaseAPI implements KsqlApiInterface {

    /**
     * executeKsql
     */
    async executeKsqlRaw(requestParameters: ExecuteKsqlRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<KsqlCommandV2Response>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling executeKsql.');
        }

        if (requestParameters.ksqlCommandV2 === null || requestParameters.ksqlCommandV2 === undefined) {
            throw new runtime.RequiredError('ksqlCommandV2','Required parameter requestParameters.ksqlCommandV2 was null or undefined when calling executeKsql.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/ksql/v2`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KsqlCommandV2ToJSON(requestParameters.ksqlCommandV2),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KsqlCommandV2ResponseFromJSON(jsonValue));
    }

    /**
     * executeKsql
     */
    async executeKsql(requestParameters: ExecuteKsqlRequest, initOverrides?: RequestInit): Promise<KsqlCommandV2Response> {
        const response = await this.executeKsqlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * listStreams
     */
    async listStreamsRaw(requestParameters: ListStreamsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<KsqlStreamDescription>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling listStreams.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/ksql/streams`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(KsqlStreamDescriptionFromJSON));
    }

    /**
     * listStreams
     */
    async listStreams(requestParameters: ListStreamsRequest, initOverrides?: RequestInit): Promise<Array<KsqlStreamDescription>> {
        const response = await this.listStreamsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * listTables
     */
    async listTablesRaw(requestParameters: ListTablesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<KsqlTableDescription>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling listTables.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/ksql/tables`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(KsqlTableDescriptionFromJSON));
    }

    /**
     * listTables
     */
    async listTables(requestParameters: ListTablesRequest, initOverrides?: RequestInit): Promise<Array<KsqlTableDescription>> {
        const response = await this.listTablesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * openKsqlResponsePipe
     */
    async openKsqlResponsePipeRaw(requestParameters: OpenKsqlResponsePipeRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<KsqlResponse>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling openKsqlResponsePipe.');
        }

        if (requestParameters.pipeId === null || requestParameters.pipeId === undefined) {
            throw new runtime.RequiredError('pipeId','Required parameter requestParameters.pipeId was null or undefined when calling openKsqlResponsePipe.');
        }

        const queryParameters: any = {};

        if (requestParameters.pipeId !== undefined) {
            queryParameters['pipeId'] = requestParameters.pipeId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/ksql/response`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(KsqlResponseFromJSON));
    }

    /**
     * openKsqlResponsePipe
     */
    async openKsqlResponsePipe(requestParameters: OpenKsqlResponsePipeRequest, initOverrides?: RequestInit): Promise<Array<KsqlResponse>> {
        const response = await this.openKsqlResponsePipeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
