/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ApiNotFoundResponse,
    ApiNotFoundResponseFromJSON,
    ApiNotFoundResponseToJSON,
    CreateTopicMessage,
    CreateTopicMessageFromJSON,
    CreateTopicMessageToJSON,
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    MessageFilterId,
    MessageFilterIdFromJSON,
    MessageFilterIdToJSON,
    MessageFilterRegistration,
    MessageFilterRegistrationFromJSON,
    MessageFilterRegistrationToJSON,
    MessageFilterType,
    MessageFilterTypeFromJSON,
    MessageFilterTypeToJSON,
    PollingMode,
    PollingModeFromJSON,
    PollingModeToJSON,
    SeekDirection,
    SeekDirectionFromJSON,
    SeekDirectionToJSON,
    SeekType,
    SeekTypeFromJSON,
    SeekTypeToJSON,
    SerdeUsage,
    SerdeUsageFromJSON,
    SerdeUsageToJSON,
    SmartFilterTestExecution,
    SmartFilterTestExecutionFromJSON,
    SmartFilterTestExecutionToJSON,
    SmartFilterTestExecutionResult,
    SmartFilterTestExecutionResultFromJSON,
    SmartFilterTestExecutionResultToJSON,
    TopicMessageEvent,
    TopicMessageEventFromJSON,
    TopicMessageEventToJSON,
    TopicSerdeSuggestion,
    TopicSerdeSuggestionFromJSON,
    TopicSerdeSuggestionToJSON,
} from '../models';

export interface DeleteTopicMessagesRequest {
    clusterName: string;
    topicName: string;
    partitions?: Array<number>;
}

export interface ExecuteSmartFilterTestRequest {
    smartFilterTestExecution: SmartFilterTestExecution;
}

export interface GetSerdesRequest {
    clusterName: string;
    topicName: string;
    use: SerdeUsage;
}

export interface GetTopicMessagesRequest {
    clusterName: string;
    topicName: string;
    seekType?: SeekType;
    seekTo?: Array<string>;
    limit?: number;
    q?: string;
    filterQueryType?: MessageFilterType;
    seekDirection?: SeekDirection;
    keySerde?: string;
    valueSerde?: string;
}

export interface GetTopicMessagesV2Request {
    clusterName: string;
    topicName: string;
    mode?: PollingMode;
    partitions?: Array<number>;
    limit?: number;
    stringFilter?: string;
    smartFilterId?: string;
    offset?: number;
    timestamp?: number;
    keySerde?: string;
    valueSerde?: string;
    cursor?: string;
}

export interface RegisterFilterRequest {
    clusterName: string;
    topicName: string;
    messageFilterRegistration: MessageFilterRegistration;
}

export interface SendTopicMessagesRequest {
    clusterName: string;
    topicName: string;
    createTopicMessage: CreateTopicMessage;
}

/**
 * MessagesApi - interface
 * 
 * @export
 * @interface MessagesApiInterface
 */
export interface MessagesApiInterface {
    /**
     * 
     * @summary deleteTopicMessages
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {Array<number>} [partitions] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    deleteTopicMessagesRaw(requestParameters: DeleteTopicMessagesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * deleteTopicMessages
     */
    deleteTopicMessages(requestParameters: DeleteTopicMessagesRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary executeSmartFilterTest
     * @param {SmartFilterTestExecution} smartFilterTestExecution 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    executeSmartFilterTestRaw(requestParameters: ExecuteSmartFilterTestRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SmartFilterTestExecutionResult>>;

    /**
     * executeSmartFilterTest
     */
    executeSmartFilterTest(requestParameters: ExecuteSmartFilterTestRequest, initOverrides?: RequestInit): Promise<SmartFilterTestExecutionResult>;

    /**
     * 
     * @summary getSerdes
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {SerdeUsage} use 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    getSerdesRaw(requestParameters: GetSerdesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<TopicSerdeSuggestion>>;

    /**
     * getSerdes
     */
    getSerdes(requestParameters: GetSerdesRequest, initOverrides?: RequestInit): Promise<TopicSerdeSuggestion>;

    /**
     * 
     * @summary getTopicMessages
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {SeekType} [seekType] 
     * @param {Array<string>} [seekTo] 
     * @param {number} [limit] 
     * @param {string} [q] 
     * @param {MessageFilterType} [filterQueryType] 
     * @param {SeekDirection} [seekDirection] 
     * @param {string} [keySerde] 
     * @param {string} [valueSerde] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    getTopicMessagesRaw(requestParameters: GetTopicMessagesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<TopicMessageEvent>>>;

    /**
     * getTopicMessages
     */
    getTopicMessages(requestParameters: GetTopicMessagesRequest, initOverrides?: RequestInit): Promise<Array<TopicMessageEvent>>;

    /**
     * 
     * @summary getTopicMessagesV2
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {PollingMode} [mode] 
     * @param {Array<number>} [partitions] 
     * @param {number} [limit] 
     * @param {string} [stringFilter] 
     * @param {string} [smartFilterId] 
     * @param {number} [offset] 
     * @param {number} [timestamp] 
     * @param {string} [keySerde] 
     * @param {string} [valueSerde] 
     * @param {string} [cursor] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    getTopicMessagesV2Raw(requestParameters: GetTopicMessagesV2Request, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<TopicMessageEvent>>>;

    /**
     * getTopicMessagesV2
     */
    getTopicMessagesV2(requestParameters: GetTopicMessagesV2Request, initOverrides?: RequestInit): Promise<Array<TopicMessageEvent>>;

    /**
     * 
     * @summary registerFilter
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {MessageFilterRegistration} messageFilterRegistration 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    registerFilterRaw(requestParameters: RegisterFilterRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<MessageFilterId>>;

    /**
     * registerFilter
     */
    registerFilter(requestParameters: RegisterFilterRequest, initOverrides?: RequestInit): Promise<MessageFilterId>;

    /**
     * 
     * @summary sendTopicMessages
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {CreateTopicMessage} createTopicMessage 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    sendTopicMessagesRaw(requestParameters: SendTopicMessagesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * sendTopicMessages
     */
    sendTopicMessages(requestParameters: SendTopicMessagesRequest, initOverrides?: RequestInit): Promise<void>;

}

/**
 * 
 */
export class MessagesApi extends runtime.BaseAPI implements MessagesApiInterface {

    /**
     * deleteTopicMessages
     */
    async deleteTopicMessagesRaw(requestParameters: DeleteTopicMessagesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling deleteTopicMessages.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling deleteTopicMessages.');
        }

        const queryParameters: any = {};

        if (requestParameters.partitions) {
            queryParameters['partitions'] = requestParameters.partitions.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/messages`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * deleteTopicMessages
     */
    async deleteTopicMessages(requestParameters: DeleteTopicMessagesRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteTopicMessagesRaw(requestParameters, initOverrides);
    }

    /**
     * executeSmartFilterTest
     */
    async executeSmartFilterTestRaw(requestParameters: ExecuteSmartFilterTestRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SmartFilterTestExecutionResult>> {
        if (requestParameters.smartFilterTestExecution === null || requestParameters.smartFilterTestExecution === undefined) {
            throw new runtime.RequiredError('smartFilterTestExecution','Required parameter requestParameters.smartFilterTestExecution was null or undefined when calling executeSmartFilterTest.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/smartfilters/testexecutions`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SmartFilterTestExecutionToJSON(requestParameters.smartFilterTestExecution),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SmartFilterTestExecutionResultFromJSON(jsonValue));
    }

    /**
     * executeSmartFilterTest
     */
    async executeSmartFilterTest(requestParameters: ExecuteSmartFilterTestRequest, initOverrides?: RequestInit): Promise<SmartFilterTestExecutionResult> {
        const response = await this.executeSmartFilterTestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getSerdes
     */
    async getSerdesRaw(requestParameters: GetSerdesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<TopicSerdeSuggestion>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getSerdes.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling getSerdes.');
        }

        if (requestParameters.use === null || requestParameters.use === undefined) {
            throw new runtime.RequiredError('use','Required parameter requestParameters.use was null or undefined when calling getSerdes.');
        }

        const queryParameters: any = {};

        if (requestParameters.use !== undefined) {
            queryParameters['use'] = requestParameters.use;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/serdes`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TopicSerdeSuggestionFromJSON(jsonValue));
    }

    /**
     * getSerdes
     */
    async getSerdes(requestParameters: GetSerdesRequest, initOverrides?: RequestInit): Promise<TopicSerdeSuggestion> {
        const response = await this.getSerdesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getTopicMessages
     */
    async getTopicMessagesRaw(requestParameters: GetTopicMessagesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<TopicMessageEvent>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getTopicMessages.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling getTopicMessages.');
        }

        const queryParameters: any = {};

        if (requestParameters.seekType !== undefined) {
            queryParameters['seekType'] = requestParameters.seekType;
        }

        if (requestParameters.seekTo) {
            queryParameters['seekTo'] = requestParameters.seekTo.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.q !== undefined) {
            queryParameters['q'] = requestParameters.q;
        }

        if (requestParameters.filterQueryType !== undefined) {
            queryParameters['filterQueryType'] = requestParameters.filterQueryType;
        }

        if (requestParameters.seekDirection !== undefined) {
            queryParameters['seekDirection'] = requestParameters.seekDirection;
        }

        if (requestParameters.keySerde !== undefined) {
            queryParameters['keySerde'] = requestParameters.keySerde;
        }

        if (requestParameters.valueSerde !== undefined) {
            queryParameters['valueSerde'] = requestParameters.valueSerde;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/messages`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TopicMessageEventFromJSON));
    }

    /**
     * getTopicMessages
     */
    async getTopicMessages(requestParameters: GetTopicMessagesRequest, initOverrides?: RequestInit): Promise<Array<TopicMessageEvent>> {
        const response = await this.getTopicMessagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getTopicMessagesV2
     */
    async getTopicMessagesV2Raw(requestParameters: GetTopicMessagesV2Request, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<TopicMessageEvent>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getTopicMessagesV2.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling getTopicMessagesV2.');
        }

        const queryParameters: any = {};

        if (requestParameters.mode !== undefined) {
            queryParameters['mode'] = requestParameters.mode;
        }

        if (requestParameters.partitions) {
            queryParameters['partitions'] = requestParameters.partitions.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.stringFilter !== undefined) {
            queryParameters['stringFilter'] = requestParameters.stringFilter;
        }

        if (requestParameters.smartFilterId !== undefined) {
            queryParameters['smartFilterId'] = requestParameters.smartFilterId;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.timestamp !== undefined) {
            queryParameters['timestamp'] = requestParameters.timestamp;
        }

        if (requestParameters.keySerde !== undefined) {
            queryParameters['keySerde'] = requestParameters.keySerde;
        }

        if (requestParameters.valueSerde !== undefined) {
            queryParameters['valueSerde'] = requestParameters.valueSerde;
        }

        if (requestParameters.cursor !== undefined) {
            queryParameters['cursor'] = requestParameters.cursor;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/messages/v2`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TopicMessageEventFromJSON));
    }

    /**
     * getTopicMessagesV2
     */
    async getTopicMessagesV2(requestParameters: GetTopicMessagesV2Request, initOverrides?: RequestInit): Promise<Array<TopicMessageEvent>> {
        const response = await this.getTopicMessagesV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * registerFilter
     */
    async registerFilterRaw(requestParameters: RegisterFilterRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<MessageFilterId>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling registerFilter.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling registerFilter.');
        }

        if (requestParameters.messageFilterRegistration === null || requestParameters.messageFilterRegistration === undefined) {
            throw new runtime.RequiredError('messageFilterRegistration','Required parameter requestParameters.messageFilterRegistration was null or undefined when calling registerFilter.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/smartfilters`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MessageFilterRegistrationToJSON(requestParameters.messageFilterRegistration),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageFilterIdFromJSON(jsonValue));
    }

    /**
     * registerFilter
     */
    async registerFilter(requestParameters: RegisterFilterRequest, initOverrides?: RequestInit): Promise<MessageFilterId> {
        const response = await this.registerFilterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * sendTopicMessages
     */
    async sendTopicMessagesRaw(requestParameters: SendTopicMessagesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling sendTopicMessages.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling sendTopicMessages.');
        }

        if (requestParameters.createTopicMessage === null || requestParameters.createTopicMessage === undefined) {
            throw new runtime.RequiredError('createTopicMessage','Required parameter requestParameters.createTopicMessage was null or undefined when calling sendTopicMessages.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/messages`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTopicMessageToJSON(requestParameters.createTopicMessage),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * sendTopicMessages
     */
    async sendTopicMessages(requestParameters: SendTopicMessagesRequest, initOverrides?: RequestInit): Promise<void> {
        await this.sendTopicMessagesRaw(requestParameters, initOverrides);
    }

}
