/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface ExposeClusterMetricsRequest {
    clusterName: string;
}

/**
 * PrometheusExposeApi - interface
 * 
 * @export
 * @interface PrometheusExposeApiInterface
 */
export interface PrometheusExposeApiInterface {
    /**
     * 
     * @summary exposeAllMetrics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrometheusExposeApiInterface
     */
    exposeAllMetricsRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>>;

    /**
     * exposeAllMetrics
     */
    exposeAllMetrics(initOverrides?: RequestInit): Promise<string>;

    /**
     * 
     * @summary exposeClusterMetrics
     * @param {string} clusterName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrometheusExposeApiInterface
     */
    exposeClusterMetricsRaw(requestParameters: ExposeClusterMetricsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>>;

    /**
     * exposeClusterMetrics
     */
    exposeClusterMetrics(requestParameters: ExposeClusterMetricsRequest, initOverrides?: RequestInit): Promise<string>;

}

/**
 * 
 */
export class PrometheusExposeApi extends runtime.BaseAPI implements PrometheusExposeApiInterface {

    /**
     * exposeAllMetrics
     */
    async exposeAllMetricsRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/metrics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * exposeAllMetrics
     */
    async exposeAllMetrics(initOverrides?: RequestInit): Promise<string> {
        const response = await this.exposeAllMetricsRaw(initOverrides);
        return await response.value();
    }

    /**
     * exposeClusterMetrics
     */
    async exposeClusterMetricsRaw(requestParameters: ExposeClusterMetricsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling exposeClusterMetrics.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/metrics/{clusterName}`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * exposeClusterMetrics
     */
    async exposeClusterMetrics(requestParameters: ExposeClusterMetricsRequest, initOverrides?: RequestInit): Promise<string> {
        const response = await this.exposeClusterMetricsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
