/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ApiNotFoundResponse,
    ApiNotFoundResponseFromJSON,
    ApiNotFoundResponseToJSON,
    ApiTimeoutResponse,
    ApiTimeoutResponseFromJSON,
    ApiTimeoutResponseToJSON,
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    FullConnectorInfo,
    FullConnectorInfoFromJSON,
    FullConnectorInfoToJSON,
    KafkaAcl,
    KafkaAclFromJSON,
    KafkaAclToJSON,
    PartitionsIncrease,
    PartitionsIncreaseFromJSON,
    PartitionsIncreaseToJSON,
    PartitionsIncreaseResponse,
    PartitionsIncreaseResponseFromJSON,
    PartitionsIncreaseResponseToJSON,
    ReplicationFactorChange,
    ReplicationFactorChangeFromJSON,
    ReplicationFactorChangeToJSON,
    ReplicationFactorChangeResponse,
    ReplicationFactorChangeResponseFromJSON,
    ReplicationFactorChangeResponseToJSON,
    SortOrder,
    SortOrderFromJSON,
    SortOrderToJSON,
    Topic,
    TopicFromJSON,
    TopicToJSON,
    TopicAnalysis,
    TopicAnalysisFromJSON,
    TopicAnalysisToJSON,
    TopicColumnsToSort,
    TopicColumnsToSortFromJSON,
    TopicColumnsToSortToJSON,
    TopicConfig,
    TopicConfigFromJSON,
    TopicConfigToJSON,
    TopicCreation,
    TopicCreationFromJSON,
    TopicCreationToJSON,
    TopicDetails,
    TopicDetailsFromJSON,
    TopicDetailsToJSON,
    TopicProducerState,
    TopicProducerStateFromJSON,
    TopicProducerStateToJSON,
    TopicUpdate,
    TopicUpdateFromJSON,
    TopicUpdateToJSON,
    TopicsResponse,
    TopicsResponseFromJSON,
    TopicsResponseToJSON,
} from '../models';

export interface AnalyzeTopicRequest {
    clusterName: string;
    topicName: string;
}

export interface CancelTopicAnalysisRequest {
    clusterName: string;
    topicName: string;
}

export interface ChangeReplicationFactorRequest {
    clusterName: string;
    topicName: string;
    replicationFactorChange: ReplicationFactorChange;
}

export interface CloneTopicRequest {
    clusterName: string;
    topicName: string;
    newTopicName: string;
}

export interface CreateTopicRequest {
    clusterName: string;
    topicCreation: TopicCreation;
}

export interface DeleteTopicRequest {
    clusterName: string;
    topicName: string;
}

export interface GetActiveProducerStatesRequest {
    clusterName: string;
    topicName: string;
}

export interface GetTopicAnalysisRequest {
    clusterName: string;
    topicName: string;
}

export interface GetTopicConfigsRequest {
    clusterName: string;
    topicName: string;
}

export interface GetTopicConnectorsRequest {
    clusterName: string;
    topicName: string;
}

export interface GetTopicDetailsRequest {
    clusterName: string;
    topicName: string;
}

export interface GetTopicsRequest {
    clusterName: string;
    page?: number;
    perPage?: number;
    showInternal?: boolean;
    search?: string;
    orderBy?: TopicColumnsToSort;
    sortOrder?: SortOrder;
    fts?: boolean;
}

export interface GetTopicsCsvRequest {
    clusterName: string;
    showInternal?: boolean;
    search?: string;
    orderBy?: TopicColumnsToSort;
    sortOrder?: SortOrder;
    fts?: boolean;
}

export interface IncreaseTopicPartitionsRequest {
    clusterName: string;
    topicName: string;
    partitionsIncrease: PartitionsIncrease;
}

export interface ListTopicAclsRequest {
    clusterName: string;
    topicName: string;
}

export interface RecreateTopicRequest {
    clusterName: string;
    topicName: string;
}

export interface UpdateTopicRequest {
    clusterName: string;
    topicName: string;
    topicUpdate: TopicUpdate;
}

/**
 * TopicsApi - interface
 * 
 * @export
 * @interface TopicsApiInterface
 */
export interface TopicsApiInterface {
    /**
     * 
     * @summary analyzeTopic
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    analyzeTopicRaw(requestParameters: AnalyzeTopicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * analyzeTopic
     */
    analyzeTopic(requestParameters: AnalyzeTopicRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary cancelTopicAnalysis
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    cancelTopicAnalysisRaw(requestParameters: CancelTopicAnalysisRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * cancelTopicAnalysis
     */
    cancelTopicAnalysis(requestParameters: CancelTopicAnalysisRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary changeReplicationFactor
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {ReplicationFactorChange} replicationFactorChange 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    changeReplicationFactorRaw(requestParameters: ChangeReplicationFactorRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReplicationFactorChangeResponse>>;

    /**
     * changeReplicationFactor
     */
    changeReplicationFactor(requestParameters: ChangeReplicationFactorRequest, initOverrides?: RequestInit): Promise<ReplicationFactorChangeResponse>;

    /**
     * 
     * @summary cloneTopic
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {string} newTopicName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    cloneTopicRaw(requestParameters: CloneTopicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Topic>>;

    /**
     * cloneTopic
     */
    cloneTopic(requestParameters: CloneTopicRequest, initOverrides?: RequestInit): Promise<Topic>;

    /**
     * 
     * @summary createTopic
     * @param {string} clusterName 
     * @param {TopicCreation} topicCreation 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    createTopicRaw(requestParameters: CreateTopicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Topic>>;

    /**
     * createTopic
     */
    createTopic(requestParameters: CreateTopicRequest, initOverrides?: RequestInit): Promise<Topic>;

    /**
     * 
     * @summary deleteTopic
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    deleteTopicRaw(requestParameters: DeleteTopicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * deleteTopic
     */
    deleteTopic(requestParameters: DeleteTopicRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @summary getActiveProducerStates
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    getActiveProducerStatesRaw(requestParameters: GetActiveProducerStatesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<TopicProducerState>>>;

    /**
     * getActiveProducerStates
     */
    getActiveProducerStates(requestParameters: GetActiveProducerStatesRequest, initOverrides?: RequestInit): Promise<Array<TopicProducerState>>;

    /**
     * 
     * @summary getTopicAnalysis
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    getTopicAnalysisRaw(requestParameters: GetTopicAnalysisRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<TopicAnalysis>>;

    /**
     * getTopicAnalysis
     */
    getTopicAnalysis(requestParameters: GetTopicAnalysisRequest, initOverrides?: RequestInit): Promise<TopicAnalysis>;

    /**
     * 
     * @summary getTopicConfigs
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    getTopicConfigsRaw(requestParameters: GetTopicConfigsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<TopicConfig>>>;

    /**
     * getTopicConfigs
     */
    getTopicConfigs(requestParameters: GetTopicConfigsRequest, initOverrides?: RequestInit): Promise<Array<TopicConfig>>;

    /**
     * 
     * @summary getTopicConnectors
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    getTopicConnectorsRaw(requestParameters: GetTopicConnectorsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<FullConnectorInfo>>>;

    /**
     * getTopicConnectors
     */
    getTopicConnectors(requestParameters: GetTopicConnectorsRequest, initOverrides?: RequestInit): Promise<Array<FullConnectorInfo>>;

    /**
     * 
     * @summary getTopicDetails
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    getTopicDetailsRaw(requestParameters: GetTopicDetailsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<TopicDetails>>;

    /**
     * getTopicDetails
     */
    getTopicDetails(requestParameters: GetTopicDetailsRequest, initOverrides?: RequestInit): Promise<TopicDetails>;

    /**
     * 
     * @summary getTopics
     * @param {string} clusterName 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {boolean} [showInternal] 
     * @param {string} [search] 
     * @param {TopicColumnsToSort} [orderBy] 
     * @param {SortOrder} [sortOrder] 
     * @param {boolean} [fts] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    getTopicsRaw(requestParameters: GetTopicsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<TopicsResponse>>;

    /**
     * getTopics
     */
    getTopics(requestParameters: GetTopicsRequest, initOverrides?: RequestInit): Promise<TopicsResponse>;

    /**
     * 
     * @summary getTopics
     * @param {string} clusterName 
     * @param {boolean} [showInternal] 
     * @param {string} [search] 
     * @param {TopicColumnsToSort} [orderBy] 
     * @param {SortOrder} [sortOrder] 
     * @param {boolean} [fts] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    getTopicsCsvRaw(requestParameters: GetTopicsCsvRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>>;

    /**
     * getTopics
     */
    getTopicsCsv(requestParameters: GetTopicsCsvRequest, initOverrides?: RequestInit): Promise<string>;

    /**
     * 
     * @summary increaseTopicPartitions
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {PartitionsIncrease} partitionsIncrease 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    increaseTopicPartitionsRaw(requestParameters: IncreaseTopicPartitionsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<PartitionsIncreaseResponse>>;

    /**
     * increaseTopicPartitions
     */
    increaseTopicPartitions(requestParameters: IncreaseTopicPartitionsRequest, initOverrides?: RequestInit): Promise<PartitionsIncreaseResponse>;

    /**
     * 
     * @summary listTopicAcls
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    listTopicAclsRaw(requestParameters: ListTopicAclsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<KafkaAcl>>>;

    /**
     * listTopicAcls
     */
    listTopicAcls(requestParameters: ListTopicAclsRequest, initOverrides?: RequestInit): Promise<Array<KafkaAcl>>;

    /**
     * 
     * @summary recreateTopic
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    recreateTopicRaw(requestParameters: RecreateTopicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Topic>>;

    /**
     * recreateTopic
     */
    recreateTopic(requestParameters: RecreateTopicRequest, initOverrides?: RequestInit): Promise<Topic>;

    /**
     * 
     * @summary updateTopic
     * @param {string} clusterName 
     * @param {string} topicName 
     * @param {TopicUpdate} topicUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TopicsApiInterface
     */
    updateTopicRaw(requestParameters: UpdateTopicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Topic>>;

    /**
     * updateTopic
     */
    updateTopic(requestParameters: UpdateTopicRequest, initOverrides?: RequestInit): Promise<Topic>;

}

/**
 * 
 */
export class TopicsApi extends runtime.BaseAPI implements TopicsApiInterface {

    /**
     * analyzeTopic
     */
    async analyzeTopicRaw(requestParameters: AnalyzeTopicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling analyzeTopic.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling analyzeTopic.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/analysis`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * analyzeTopic
     */
    async analyzeTopic(requestParameters: AnalyzeTopicRequest, initOverrides?: RequestInit): Promise<void> {
        await this.analyzeTopicRaw(requestParameters, initOverrides);
    }

    /**
     * cancelTopicAnalysis
     */
    async cancelTopicAnalysisRaw(requestParameters: CancelTopicAnalysisRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling cancelTopicAnalysis.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling cancelTopicAnalysis.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/analysis`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * cancelTopicAnalysis
     */
    async cancelTopicAnalysis(requestParameters: CancelTopicAnalysisRequest, initOverrides?: RequestInit): Promise<void> {
        await this.cancelTopicAnalysisRaw(requestParameters, initOverrides);
    }

    /**
     * changeReplicationFactor
     */
    async changeReplicationFactorRaw(requestParameters: ChangeReplicationFactorRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ReplicationFactorChangeResponse>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling changeReplicationFactor.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling changeReplicationFactor.');
        }

        if (requestParameters.replicationFactorChange === null || requestParameters.replicationFactorChange === undefined) {
            throw new runtime.RequiredError('replicationFactorChange','Required parameter requestParameters.replicationFactorChange was null or undefined when calling changeReplicationFactor.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/replications`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ReplicationFactorChangeToJSON(requestParameters.replicationFactorChange),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReplicationFactorChangeResponseFromJSON(jsonValue));
    }

    /**
     * changeReplicationFactor
     */
    async changeReplicationFactor(requestParameters: ChangeReplicationFactorRequest, initOverrides?: RequestInit): Promise<ReplicationFactorChangeResponse> {
        const response = await this.changeReplicationFactorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * cloneTopic
     */
    async cloneTopicRaw(requestParameters: CloneTopicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Topic>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling cloneTopic.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling cloneTopic.');
        }

        if (requestParameters.newTopicName === null || requestParameters.newTopicName === undefined) {
            throw new runtime.RequiredError('newTopicName','Required parameter requestParameters.newTopicName was null or undefined when calling cloneTopic.');
        }

        const queryParameters: any = {};

        if (requestParameters.newTopicName !== undefined) {
            queryParameters['newTopicName'] = requestParameters.newTopicName;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/clone`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TopicFromJSON(jsonValue));
    }

    /**
     * cloneTopic
     */
    async cloneTopic(requestParameters: CloneTopicRequest, initOverrides?: RequestInit): Promise<Topic> {
        const response = await this.cloneTopicRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * createTopic
     */
    async createTopicRaw(requestParameters: CreateTopicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Topic>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling createTopic.');
        }

        if (requestParameters.topicCreation === null || requestParameters.topicCreation === undefined) {
            throw new runtime.RequiredError('topicCreation','Required parameter requestParameters.topicCreation was null or undefined when calling createTopic.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TopicCreationToJSON(requestParameters.topicCreation),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TopicFromJSON(jsonValue));
    }

    /**
     * createTopic
     */
    async createTopic(requestParameters: CreateTopicRequest, initOverrides?: RequestInit): Promise<Topic> {
        const response = await this.createTopicRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * deleteTopic
     */
    async deleteTopicRaw(requestParameters: DeleteTopicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling deleteTopic.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling deleteTopic.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * deleteTopic
     */
    async deleteTopic(requestParameters: DeleteTopicRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteTopicRaw(requestParameters, initOverrides);
    }

    /**
     * getActiveProducerStates
     */
    async getActiveProducerStatesRaw(requestParameters: GetActiveProducerStatesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<TopicProducerState>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getActiveProducerStates.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling getActiveProducerStates.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/activeproducers`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TopicProducerStateFromJSON));
    }

    /**
     * getActiveProducerStates
     */
    async getActiveProducerStates(requestParameters: GetActiveProducerStatesRequest, initOverrides?: RequestInit): Promise<Array<TopicProducerState>> {
        const response = await this.getActiveProducerStatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getTopicAnalysis
     */
    async getTopicAnalysisRaw(requestParameters: GetTopicAnalysisRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<TopicAnalysis>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getTopicAnalysis.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling getTopicAnalysis.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/analysis`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TopicAnalysisFromJSON(jsonValue));
    }

    /**
     * getTopicAnalysis
     */
    async getTopicAnalysis(requestParameters: GetTopicAnalysisRequest, initOverrides?: RequestInit): Promise<TopicAnalysis> {
        const response = await this.getTopicAnalysisRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getTopicConfigs
     */
    async getTopicConfigsRaw(requestParameters: GetTopicConfigsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<TopicConfig>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getTopicConfigs.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling getTopicConfigs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/config`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TopicConfigFromJSON));
    }

    /**
     * getTopicConfigs
     */
    async getTopicConfigs(requestParameters: GetTopicConfigsRequest, initOverrides?: RequestInit): Promise<Array<TopicConfig>> {
        const response = await this.getTopicConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getTopicConnectors
     */
    async getTopicConnectorsRaw(requestParameters: GetTopicConnectorsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<FullConnectorInfo>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getTopicConnectors.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling getTopicConnectors.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/connectors`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FullConnectorInfoFromJSON));
    }

    /**
     * getTopicConnectors
     */
    async getTopicConnectors(requestParameters: GetTopicConnectorsRequest, initOverrides?: RequestInit): Promise<Array<FullConnectorInfo>> {
        const response = await this.getTopicConnectorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getTopicDetails
     */
    async getTopicDetailsRaw(requestParameters: GetTopicDetailsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<TopicDetails>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getTopicDetails.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling getTopicDetails.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TopicDetailsFromJSON(jsonValue));
    }

    /**
     * getTopicDetails
     */
    async getTopicDetails(requestParameters: GetTopicDetailsRequest, initOverrides?: RequestInit): Promise<TopicDetails> {
        const response = await this.getTopicDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getTopics
     */
    async getTopicsRaw(requestParameters: GetTopicsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<TopicsResponse>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getTopics.');
        }

        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['perPage'] = requestParameters.perPage;
        }

        if (requestParameters.showInternal !== undefined) {
            queryParameters['showInternal'] = requestParameters.showInternal;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        if (requestParameters.orderBy !== undefined) {
            queryParameters['orderBy'] = requestParameters.orderBy;
        }

        if (requestParameters.sortOrder !== undefined) {
            queryParameters['sortOrder'] = requestParameters.sortOrder;
        }

        if (requestParameters.fts !== undefined) {
            queryParameters['fts'] = requestParameters.fts;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TopicsResponseFromJSON(jsonValue));
    }

    /**
     * getTopics
     */
    async getTopics(requestParameters: GetTopicsRequest, initOverrides?: RequestInit): Promise<TopicsResponse> {
        const response = await this.getTopicsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getTopics
     */
    async getTopicsCsvRaw(requestParameters: GetTopicsCsvRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getTopicsCsv.');
        }

        const queryParameters: any = {};

        if (requestParameters.showInternal !== undefined) {
            queryParameters['showInternal'] = requestParameters.showInternal;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        if (requestParameters.orderBy !== undefined) {
            queryParameters['orderBy'] = requestParameters.orderBy;
        }

        if (requestParameters.sortOrder !== undefined) {
            queryParameters['sortOrder'] = requestParameters.sortOrder;
        }

        if (requestParameters.fts !== undefined) {
            queryParameters['fts'] = requestParameters.fts;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/csv`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * getTopics
     */
    async getTopicsCsv(requestParameters: GetTopicsCsvRequest, initOverrides?: RequestInit): Promise<string> {
        const response = await this.getTopicsCsvRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * increaseTopicPartitions
     */
    async increaseTopicPartitionsRaw(requestParameters: IncreaseTopicPartitionsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<PartitionsIncreaseResponse>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling increaseTopicPartitions.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling increaseTopicPartitions.');
        }

        if (requestParameters.partitionsIncrease === null || requestParameters.partitionsIncrease === undefined) {
            throw new runtime.RequiredError('partitionsIncrease','Required parameter requestParameters.partitionsIncrease was null or undefined when calling increaseTopicPartitions.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/partitions`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PartitionsIncreaseToJSON(requestParameters.partitionsIncrease),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PartitionsIncreaseResponseFromJSON(jsonValue));
    }

    /**
     * increaseTopicPartitions
     */
    async increaseTopicPartitions(requestParameters: IncreaseTopicPartitionsRequest, initOverrides?: RequestInit): Promise<PartitionsIncreaseResponse> {
        const response = await this.increaseTopicPartitionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * listTopicAcls
     */
    async listTopicAclsRaw(requestParameters: ListTopicAclsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<KafkaAcl>>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling listTopicAcls.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling listTopicAcls.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}/acls`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(KafkaAclFromJSON));
    }

    /**
     * listTopicAcls
     */
    async listTopicAcls(requestParameters: ListTopicAclsRequest, initOverrides?: RequestInit): Promise<Array<KafkaAcl>> {
        const response = await this.listTopicAclsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * recreateTopic
     */
    async recreateTopicRaw(requestParameters: RecreateTopicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Topic>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling recreateTopic.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling recreateTopic.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TopicFromJSON(jsonValue));
    }

    /**
     * recreateTopic
     */
    async recreateTopic(requestParameters: RecreateTopicRequest, initOverrides?: RequestInit): Promise<Topic> {
        const response = await this.recreateTopicRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * updateTopic
     */
    async updateTopicRaw(requestParameters: UpdateTopicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Topic>> {
        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling updateTopic.');
        }

        if (requestParameters.topicName === null || requestParameters.topicName === undefined) {
            throw new runtime.RequiredError('topicName','Required parameter requestParameters.topicName was null or undefined when calling updateTopic.');
        }

        if (requestParameters.topicUpdate === null || requestParameters.topicUpdate === undefined) {
            throw new runtime.RequiredError('topicUpdate','Required parameter requestParameters.topicUpdate was null or undefined when calling updateTopic.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/clusters/{clusterName}/topics/{topicName}`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"topicName"}}`, encodeURIComponent(String(requestParameters.topicName))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TopicUpdateToJSON(requestParameters.topicUpdate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TopicFromJSON(jsonValue));
    }

    /**
     * updateTopic
     */
    async updateTopic(requestParameters: UpdateTopicRequest, initOverrides?: RequestInit): Promise<Topic> {
        const response = await this.updateTopicRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
