/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface AuthenticateRequest {
    username?: string;
    password?: string;
}

/**
 * UnmappedApi - interface
 * 
 * @export
 * @interface UnmappedApiInterface
 */
export interface UnmappedApiInterface {
    /**
     * 
     * @summary Authenticate
     * @param {string} [username] 
     * @param {string} [password] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UnmappedApiInterface
     */
    authenticateRaw(requestParameters: AuthenticateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * Authenticate
     */
    authenticate(requestParameters: AuthenticateRequest, initOverrides?: RequestInit): Promise<void>;

}

/**
 * 
 */
export class UnmappedApi extends runtime.BaseAPI implements UnmappedApiInterface {

    /**
     * Authenticate
     */
    async authenticateRaw(requestParameters: AuthenticateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.username !== undefined) {
            formParams.append('username', requestParameters.username as any);
        }

        if (requestParameters.password !== undefined) {
            formParams.append('password', requestParameters.password as any);
        }

        const response = await this.request({
            path: `/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Authenticate
     */
    async authenticate(requestParameters: AuthenticateRequest, initOverrides?: RequestInit): Promise<void> {
        await this.authenticateRaw(requestParameters, initOverrides);
    }

}
