use std::path::{Path, PathBuf};
use url::{Origin, Url};

// Restrict native downloads to configuration blobs generated by the current
// sidecar page. Filenames are confined to the user's Downloads directory.
pub fn config_download_destination(
    url: &Url,
    sidecar: Option<&Origin>,
    directory: &Path,
    suggested: &Path,
) -> Option<PathBuf> {
    if url.scheme() != "blob" || !sidecar.is_some_and(|origin| url.origin() == *origin) {
        return None;
    }
    let filename = suggested.file_name()?.to_str()?;
    if !filename.starts_with("kafka-environments-") || !filename.ends_with(".yaml") {
        return None;
    }
    let stem = Path::new(filename).file_stem()?.to_str()?;
    let mut destination = directory.join(filename);
    let mut counter = 1;
    while destination.exists() {
        destination = directory.join(format!("{stem} ({counter}).yaml"));
        counter += 1;
    }
    Some(destination)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn saves_only_configuration_blobs_from_the_running_sidecar_without_overwriting() {
        let directory = tempfile::tempdir().unwrap();
        let origin = Url::parse("http://127.0.0.1:43210").unwrap().origin();
        let blob = Url::parse("blob:http://127.0.0.1:43210/fixture").unwrap();
        let filename = Path::new("kafka-environments-2026-09-07.yaml");
        let first =
            config_download_destination(&blob, Some(&origin), directory.path(), filename).unwrap();
        assert_eq!(first, directory.path().join(filename));
        std::fs::write(&first, "local").unwrap();
        let second =
            config_download_destination(&blob, Some(&origin), directory.path(), filename).unwrap();
        assert_ne!(first, second);
        assert_eq!(std::fs::read_to_string(first).unwrap(), "local");
        assert_eq!(second.parent(), Some(directory.path()));
        for url in [
            "blob:https://example.com/fixture",
            "blob:http://127.0.0.1:43211/fixture",
            "file:///tmp/fixture",
            "https://example.com/config.yaml",
        ] {
            assert!(
                config_download_destination(
                    &Url::parse(url).unwrap(),
                    Some(&origin),
                    directory.path(),
                    filename
                )
                .is_none()
            );
        }
        assert!(config_download_destination(&blob, None, directory.path(), filename).is_none());
        assert!(
            config_download_destination(
                &blob,
                Some(&origin),
                directory.path(),
                Path::new("unsafe.html")
            )
            .is_none()
        );
    }
}
