// genstub 从 generated/models.gen.go 的 ServerInterface 声明生成
// unimplemented.gen.go：为全部操作提供返回 501 的默认实现。
// 用法: go run ./scripts/genstub   （由 make gen-go 在 oapi-codegen 之后调用）
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
)

const (
	srcFile = "internal/api/generated/models.gen.go"
	outFile = "internal/api/generated/unimplemented.gen.go"
)

type method struct {
	name string
	sig  string // 除首参 w 外的完整参数列表源码文本，如 "r *http.Request, clusterName string"
}

func main() {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, srcFile, nil, 0)
	if err != nil {
		panic(err)
	}
	var methods []method
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok || ts.Name.Name != "ServerInterface" {
			return true
		}
		iface := ts.Type.(*ast.InterfaceType)
		for _, m := range iface.Methods.List {
			if len(m.Names) == 0 {
				continue // 嵌入接口（当前生成器不产生，防御）
			}
			ft := m.Type.(*ast.FuncType)
			var buf bytes.Buffer
			for i, p := range ft.Params.List {
				if i == 0 {
					continue // 首参恒为 w http.ResponseWriter，由模板固定
				}
				if buf.Len() > 0 {
					buf.WriteString(", ")
				}
				// 参数名统一 _（接口满足性只看类型），类型按源码原样打印
				var tbuf bytes.Buffer
				if err := printer.Fprint(&tbuf, fset, p.Type); err != nil {
					panic(err)
				}
				fmt.Fprintf(&buf, "_ %s", tbuf.String())
			}
			methods = append(methods, method{name: m.Names[0].Name, sig: buf.String()})
		}
		return false
	})
	if len(methods) == 0 {
		panic("ServerInterface not found or empty — did chi-server generation run?")
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by scripts/genstub. DO NOT EDIT.\n")
	out.WriteString("// 每个契约操作的 501 默认实现；实现某端点 = 在 api 层覆写同名方法。\n\n")
	out.WriteString("package generated\n\nimport \"net/http\"\n\n")
	out.WriteString("type UnimplementedServer struct{}\n\n")
	out.WriteString(`func writeNotImplemented(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusNotImplemented)
	_, _ = w.Write([]byte(` + "`" + `{"code":5010,"message":"endpoint not implemented in current phase"}` + "`" + `))
}` + "\n\n")
	for _, m := range methods {
		fmt.Fprintf(&out, "func (UnimplementedServer) %s(w http.ResponseWriter, %s) {\n\twriteNotImplemented(w)\n}\n\n", m.name, m.sig)
	}
	if err := os.WriteFile(outFile, out.Bytes(), 0o644); err != nil {
		panic(err)
	}
	fmt.Fprintf(os.Stderr, "genstub: %d methods -> %s\n", len(methods), outFile)
}
