/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDuplicateResponse
 */
export interface ApiDuplicateResponse {
    /**
     * 
     * @type {string}
     * @memberof ApiDuplicateResponse
     */
    message: string;
}

export function ApiDuplicateResponseFromJSON(json: any): ApiDuplicateResponse {
    return ApiDuplicateResponseFromJSONTyped(json, false);
}

export function ApiDuplicateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDuplicateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ApiDuplicateResponseToJSON(value?: ApiDuplicateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

