/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiRebalanceInProgressResponse
 */
export interface ApiRebalanceInProgressResponse {
    /**
     * 
     * @type {string}
     * @memberof ApiRebalanceInProgressResponse
     */
    message: string;
}

export function ApiRebalanceInProgressResponseFromJSON(json: any): ApiRebalanceInProgressResponse {
    return ApiRebalanceInProgressResponseFromJSONTyped(json, false);
}

export function ApiRebalanceInProgressResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRebalanceInProgressResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ApiRebalanceInProgressResponseToJSON(value?: ApiRebalanceInProgressResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

