/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesKafkaSchemaRegistrySsl
 */
export interface ApplicationConfigPropertiesKafkaSchemaRegistrySsl {
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaSchemaRegistrySsl
     */
    keystoreLocation?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaSchemaRegistrySsl
     */
    keystorePassword?: string;
}

export function ApplicationConfigPropertiesKafkaSchemaRegistrySslFromJSON(json: any): ApplicationConfigPropertiesKafkaSchemaRegistrySsl {
    return ApplicationConfigPropertiesKafkaSchemaRegistrySslFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesKafkaSchemaRegistrySslFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesKafkaSchemaRegistrySsl {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'keystoreLocation': !exists(json, 'keystoreLocation') ? undefined : json['keystoreLocation'],
        'keystorePassword': !exists(json, 'keystorePassword') ? undefined : json['keystorePassword'],
    };
}

export function ApplicationConfigPropertiesKafkaSchemaRegistrySslToJSON(value?: ApplicationConfigPropertiesKafkaSchemaRegistrySsl | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'keystoreLocation': value.keystoreLocation,
        'keystorePassword': value.keystorePassword,
    };
}

