/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesWebclient
 */
export interface ApplicationConfigPropertiesWebclient {
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesWebclient
     */
    maxInMemoryBufferSize?: string;
    /**
     * 
     * @type {number}
     * @memberof ApplicationConfigPropertiesWebclient
     */
    responseTimeoutMs?: number;
}

export function ApplicationConfigPropertiesWebclientFromJSON(json: any): ApplicationConfigPropertiesWebclient {
    return ApplicationConfigPropertiesWebclientFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesWebclientFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesWebclient {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'maxInMemoryBufferSize': !exists(json, 'maxInMemoryBufferSize') ? undefined : json['maxInMemoryBufferSize'],
        'responseTimeoutMs': !exists(json, 'responseTimeoutMs') ? undefined : json['responseTimeoutMs'],
    };
}

export function ApplicationConfigPropertiesWebclientToJSON(value?: ApplicationConfigPropertiesWebclient | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'maxInMemoryBufferSize': value.maxInMemoryBufferSize,
        'responseTimeoutMs': value.responseTimeoutMs,
    };
}

