/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationInfoBuild
 */
export interface ApplicationInfoBuild {
    /**
     * 
     * @type {string}
     * @memberof ApplicationInfoBuild
     */
    commitId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationInfoBuild
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationInfoBuild
     */
    buildTime?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationInfoBuild
     */
    isLatestRelease?: boolean;
}

export function ApplicationInfoBuildFromJSON(json: any): ApplicationInfoBuild {
    return ApplicationInfoBuildFromJSONTyped(json, false);
}

export function ApplicationInfoBuildFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationInfoBuild {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'commitId': !exists(json, 'commitId') ? undefined : json['commitId'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'buildTime': !exists(json, 'buildTime') ? undefined : json['buildTime'],
        'isLatestRelease': !exists(json, 'isLatestRelease') ? undefined : json['isLatestRelease'],
    };
}

export function ApplicationInfoBuildToJSON(value?: ApplicationInfoBuild | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'commitId': value.commitId,
        'version': value.version,
        'buildTime': value.buildTime,
        'isLatestRelease': value.isLatestRelease,
    };
}

