/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesAuthOauth2ResourceServerOpaquetoken
 */
export interface ApplicationConfigPropertiesAuthOauth2ResourceServerOpaquetoken {
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesAuthOauth2ResourceServerOpaquetoken
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesAuthOauth2ResourceServerOpaquetoken
     */
    clientSecret?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesAuthOauth2ResourceServerOpaquetoken
     */
    introspectionUri?: string;
}

export function ApplicationConfigPropertiesAuthOauth2ResourceServerOpaquetokenFromJSON(json: any): ApplicationConfigPropertiesAuthOauth2ResourceServerOpaquetoken {
    return ApplicationConfigPropertiesAuthOauth2ResourceServerOpaquetokenFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesAuthOauth2ResourceServerOpaquetokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesAuthOauth2ResourceServerOpaquetoken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientId': !exists(json, 'clientId') ? undefined : json['clientId'],
        'clientSecret': !exists(json, 'clientSecret') ? undefined : json['clientSecret'],
        'introspectionUri': !exists(json, 'introspectionUri') ? undefined : json['introspectionUri'],
    };
}

export function ApplicationConfigPropertiesAuthOauth2ResourceServerOpaquetokenToJSON(value?: ApplicationConfigPropertiesAuthOauth2ResourceServerOpaquetoken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clientId': value.clientId,
        'clientSecret': value.clientSecret,
        'introspectionUri': value.introspectionUri,
    };
}

