/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationInfoLatestRelease
 */
export interface ApplicationInfoLatestRelease {
    /**
     * 
     * @type {string}
     * @memberof ApplicationInfoLatestRelease
     */
    versionTag?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationInfoLatestRelease
     */
    publishedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationInfoLatestRelease
     */
    htmlUrl?: string;
}

export function ApplicationInfoLatestReleaseFromJSON(json: any): ApplicationInfoLatestRelease {
    return ApplicationInfoLatestReleaseFromJSONTyped(json, false);
}

export function ApplicationInfoLatestReleaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationInfoLatestRelease {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'versionTag': !exists(json, 'versionTag') ? undefined : json['versionTag'],
        'publishedAt': !exists(json, 'publishedAt') ? undefined : json['publishedAt'],
        'htmlUrl': !exists(json, 'htmlUrl') ? undefined : json['htmlUrl'],
    };
}

export function ApplicationInfoLatestReleaseToJSON(value?: ApplicationInfoLatestRelease | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'versionTag': value.versionTag,
        'publishedAt': value.publishedAt,
        'htmlUrl': value.htmlUrl,
    };
}

