/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApplicationConfigPropertiesRbacDefaultRole,
    ApplicationConfigPropertiesRbacDefaultRoleFromJSON,
    ApplicationConfigPropertiesRbacDefaultRoleFromJSONTyped,
    ApplicationConfigPropertiesRbacDefaultRoleToJSON,
    ApplicationConfigPropertiesRbacRoles,
    ApplicationConfigPropertiesRbacRolesFromJSON,
    ApplicationConfigPropertiesRbacRolesFromJSONTyped,
    ApplicationConfigPropertiesRbacRolesToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesRbac
 */
export interface ApplicationConfigPropertiesRbac {
    /**
     * 
     * @type {Array<ApplicationConfigPropertiesRbacRoles>}
     * @memberof ApplicationConfigPropertiesRbac
     */
    roles?: Array<ApplicationConfigPropertiesRbacRoles>;
    /**
     * 
     * @type {ApplicationConfigPropertiesRbacDefaultRole}
     * @memberof ApplicationConfigPropertiesRbac
     */
    defaultRole?: ApplicationConfigPropertiesRbacDefaultRole;
}

export function ApplicationConfigPropertiesRbacFromJSON(json: any): ApplicationConfigPropertiesRbac {
    return ApplicationConfigPropertiesRbacFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesRbacFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesRbac {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roles': !exists(json, 'roles') ? undefined : ((json['roles'] as Array<any>).map(ApplicationConfigPropertiesRbacRolesFromJSON)),
        'defaultRole': !exists(json, 'defaultRole') ? undefined : ApplicationConfigPropertiesRbacDefaultRoleFromJSON(json['defaultRole']),
    };
}

export function ApplicationConfigPropertiesRbacToJSON(value?: ApplicationConfigPropertiesRbac | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roles': value.roles === undefined ? undefined : ((value.roles as Array<any>).map(ApplicationConfigPropertiesRbacRolesToJSON)),
        'defaultRole': ApplicationConfigPropertiesRbacDefaultRoleToJSON(value.defaultRole),
    };
}

