/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesKafkaMasking
 */
export interface ApplicationConfigPropertiesKafkaMasking {
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaMasking
     */
    type?: ApplicationConfigPropertiesKafkaMaskingTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplicationConfigPropertiesKafkaMasking
     */
    fields?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaMasking
     */
    fieldsNamePattern?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplicationConfigPropertiesKafkaMasking
     */
    maskingCharsReplacement?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaMasking
     */
    replacement?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaMasking
     */
    topicKeysPattern?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaMasking
     */
    topicValuesPattern?: string;
}

/**
* @export
* @enum {string}
*/
export enum ApplicationConfigPropertiesKafkaMaskingTypeEnum {
    REMOVE = 'REMOVE',
    MASK = 'MASK',
    REPLACE = 'REPLACE'
}

export function ApplicationConfigPropertiesKafkaMaskingFromJSON(json: any): ApplicationConfigPropertiesKafkaMasking {
    return ApplicationConfigPropertiesKafkaMaskingFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesKafkaMaskingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesKafkaMasking {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'fields': !exists(json, 'fields') ? undefined : json['fields'],
        'fieldsNamePattern': !exists(json, 'fieldsNamePattern') ? undefined : json['fieldsNamePattern'],
        'maskingCharsReplacement': !exists(json, 'maskingCharsReplacement') ? undefined : json['maskingCharsReplacement'],
        'replacement': !exists(json, 'replacement') ? undefined : json['replacement'],
        'topicKeysPattern': !exists(json, 'topicKeysPattern') ? undefined : json['topicKeysPattern'],
        'topicValuesPattern': !exists(json, 'topicValuesPattern') ? undefined : json['topicValuesPattern'],
    };
}

export function ApplicationConfigPropertiesKafkaMaskingToJSON(value?: ApplicationConfigPropertiesKafkaMasking | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'fields': value.fields,
        'fieldsNamePattern': value.fieldsNamePattern,
        'maskingCharsReplacement': value.maskingCharsReplacement,
        'replacement': value.replacement,
        'topicKeysPattern': value.topicKeysPattern,
        'topicValuesPattern': value.topicValuesPattern,
    };
}

