/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApplicationConfigPropertiesAuthOauth2,
    ApplicationConfigPropertiesAuthOauth2FromJSON,
    ApplicationConfigPropertiesAuthOauth2FromJSONTyped,
    ApplicationConfigPropertiesAuthOauth2ToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesAuth
 */
export interface ApplicationConfigPropertiesAuth {
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesAuth
     */
    type: string;
    /**
     * 
     * @type {ApplicationConfigPropertiesAuthOauth2}
     * @memberof ApplicationConfigPropertiesAuth
     */
    oauth2?: ApplicationConfigPropertiesAuthOauth2;
}

export function ApplicationConfigPropertiesAuthFromJSON(json: any): ApplicationConfigPropertiesAuth {
    return ApplicationConfigPropertiesAuthFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesAuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesAuth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'oauth2': !exists(json, 'oauth2') ? undefined : ApplicationConfigPropertiesAuthOauth2FromJSON(json['oauth2']),
    };
}

export function ApplicationConfigPropertiesAuthToJSON(value?: ApplicationConfigPropertiesAuth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'oauth2': ApplicationConfigPropertiesAuthOauth2ToJSON(value.oauth2),
    };
}

