/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesKafkaKsqldbServerAuth
 */
export interface ApplicationConfigPropertiesKafkaKsqldbServerAuth {
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaKsqldbServerAuth
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaKsqldbServerAuth
     */
    password?: string;
}

export function ApplicationConfigPropertiesKafkaKsqldbServerAuthFromJSON(json: any): ApplicationConfigPropertiesKafkaKsqldbServerAuth {
    return ApplicationConfigPropertiesKafkaKsqldbServerAuthFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesKafkaKsqldbServerAuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesKafkaKsqldbServerAuth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function ApplicationConfigPropertiesKafkaKsqldbServerAuthToJSON(value?: ApplicationConfigPropertiesKafkaKsqldbServerAuth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}

