/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesKafkaKafkaConnect
 */
export interface ApplicationConfigPropertiesKafkaKafkaConnect {
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaKafkaConnect
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaKafkaConnect
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaKafkaConnect
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaKafkaConnect
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaKafkaConnect
     */
    keystoreLocation?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaKafkaConnect
     */
    keystorePassword?: string;
}

export function ApplicationConfigPropertiesKafkaKafkaConnectFromJSON(json: any): ApplicationConfigPropertiesKafkaKafkaConnect {
    return ApplicationConfigPropertiesKafkaKafkaConnectFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesKafkaKafkaConnectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesKafkaKafkaConnect {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'keystoreLocation': !exists(json, 'keystoreLocation') ? undefined : json['keystoreLocation'],
        'keystorePassword': !exists(json, 'keystorePassword') ? undefined : json['keystorePassword'],
    };
}

export function ApplicationConfigPropertiesKafkaKafkaConnectToJSON(value?: ApplicationConfigPropertiesKafkaKafkaConnect | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'address': value.address,
        'username': value.username,
        'password': value.password,
        'keystoreLocation': value.keystoreLocation,
        'keystorePassword': value.keystorePassword,
    };
}

