/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesKafkaSerde
 */
export interface ApplicationConfigPropertiesKafkaSerde {
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaSerde
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaSerde
     */
    className?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaSerde
     */
    filePath?: string;
    /**
     * 
     * @type {{ [key: string]: any | undefined; }}
     * @memberof ApplicationConfigPropertiesKafkaSerde
     */
    properties?: { [key: string]: any | undefined; };
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaSerde
     */
    topicKeysPattern?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaSerde
     */
    topicValuesPattern?: string;
}

export function ApplicationConfigPropertiesKafkaSerdeFromJSON(json: any): ApplicationConfigPropertiesKafkaSerde {
    return ApplicationConfigPropertiesKafkaSerdeFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesKafkaSerdeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesKafkaSerde {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'className': !exists(json, 'className') ? undefined : json['className'],
        'filePath': !exists(json, 'filePath') ? undefined : json['filePath'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
        'topicKeysPattern': !exists(json, 'topicKeysPattern') ? undefined : json['topicKeysPattern'],
        'topicValuesPattern': !exists(json, 'topicValuesPattern') ? undefined : json['topicValuesPattern'],
    };
}

export function ApplicationConfigPropertiesKafkaSerdeToJSON(value?: ApplicationConfigPropertiesKafkaSerde | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'className': value.className,
        'filePath': value.filePath,
        'properties': value.properties,
        'topicKeysPattern': value.topicKeysPattern,
        'topicValuesPattern': value.topicValuesPattern,
    };
}

