/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApplicationConfigProperties,
    ApplicationConfigPropertiesFromJSON,
    ApplicationConfigPropertiesFromJSONTyped,
    ApplicationConfigPropertiesToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApplicationConfig
 */
export interface ApplicationConfig {
    /**
     * 
     * @type {ApplicationConfigProperties}
     * @memberof ApplicationConfig
     */
    properties: ApplicationConfigProperties;
}

export function ApplicationConfigFromJSON(json: any): ApplicationConfig {
    return ApplicationConfigFromJSONTyped(json, false);
}

export function ApplicationConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'properties': ApplicationConfigPropertiesFromJSON(json['properties']),
    };
}

export function ApplicationConfigToJSON(value?: ApplicationConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'properties': ApplicationConfigPropertiesToJSON(value.properties),
    };
}

