/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApplicationConfigPropertiesRbacSubjects,
    ApplicationConfigPropertiesRbacSubjectsFromJSON,
    ApplicationConfigPropertiesRbacSubjectsFromJSONTyped,
    ApplicationConfigPropertiesRbacSubjectsToJSON,
    RbacPermission,
    RbacPermissionFromJSON,
    RbacPermissionFromJSONTyped,
    RbacPermissionToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesRbacRoles
 */
export interface ApplicationConfigPropertiesRbacRoles {
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesRbacRoles
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplicationConfigPropertiesRbacRoles
     */
    clusters?: Array<string>;
    /**
     * 
     * @type {Array<ApplicationConfigPropertiesRbacSubjects>}
     * @memberof ApplicationConfigPropertiesRbacRoles
     */
    subjects?: Array<ApplicationConfigPropertiesRbacSubjects>;
    /**
     * 
     * @type {Array<RbacPermission>}
     * @memberof ApplicationConfigPropertiesRbacRoles
     */
    permissions?: Array<RbacPermission>;
}

export function ApplicationConfigPropertiesRbacRolesFromJSON(json: any): ApplicationConfigPropertiesRbacRoles {
    return ApplicationConfigPropertiesRbacRolesFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesRbacRolesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesRbacRoles {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'clusters': !exists(json, 'clusters') ? undefined : json['clusters'],
        'subjects': !exists(json, 'subjects') ? undefined : ((json['subjects'] as Array<any>).map(ApplicationConfigPropertiesRbacSubjectsFromJSON)),
        'permissions': !exists(json, 'permissions') ? undefined : ((json['permissions'] as Array<any>).map(RbacPermissionFromJSON)),
    };
}

export function ApplicationConfigPropertiesRbacRolesToJSON(value?: ApplicationConfigPropertiesRbacRoles | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'clusters': value.clusters,
        'subjects': value.subjects === undefined ? undefined : ((value.subjects as Array<any>).map(ApplicationConfigPropertiesRbacSubjectsToJSON)),
        'permissions': value.permissions === undefined ? undefined : ((value.permissions as Array<any>).map(RbacPermissionToJSON)),
    };
}

