/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth,
    ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauthFromJSON,
    ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauthFromJSONTyped,
    ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauthToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesKafkaSchemaRegistryAuth
 */
export interface ApplicationConfigPropertiesKafkaSchemaRegistryAuth {
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaSchemaRegistryAuth
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaSchemaRegistryAuth
     */
    password?: string;
    /**
     * 
     * @type {ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth}
     * @memberof ApplicationConfigPropertiesKafkaSchemaRegistryAuth
     */
    oauth?: ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth;
}

export function ApplicationConfigPropertiesKafkaSchemaRegistryAuthFromJSON(json: any): ApplicationConfigPropertiesKafkaSchemaRegistryAuth {
    return ApplicationConfigPropertiesKafkaSchemaRegistryAuthFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesKafkaSchemaRegistryAuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesKafkaSchemaRegistryAuth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'oauth': !exists(json, 'oauth') ? undefined : ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauthFromJSON(json['oauth']),
    };
}

export function ApplicationConfigPropertiesKafkaSchemaRegistryAuthToJSON(value?: ApplicationConfigPropertiesKafkaSchemaRegistryAuth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
        'oauth': ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauthToJSON(value.oauth),
    };
}

