/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth
 */
export interface ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth {
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth
     */
    tokenUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth
     */
    clientSecret?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth
     */
    tokenCacheEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth
     */
    tokenRefreshBuffer?: string;
    /**
     * 
     * @type {number}
     * @memberof ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth
     */
    maxRetries?: number;
}

export function ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauthFromJSON(json: any): ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth {
    return ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauthFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauthFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tokenUrl': !exists(json, 'tokenUrl') ? undefined : json['tokenUrl'],
        'clientId': !exists(json, 'clientId') ? undefined : json['clientId'],
        'clientSecret': !exists(json, 'clientSecret') ? undefined : json['clientSecret'],
        'scopes': !exists(json, 'scopes') ? undefined : json['scopes'],
        'tokenCacheEnabled': !exists(json, 'tokenCacheEnabled') ? undefined : json['tokenCacheEnabled'],
        'tokenRefreshBuffer': !exists(json, 'tokenRefreshBuffer') ? undefined : json['tokenRefreshBuffer'],
        'maxRetries': !exists(json, 'maxRetries') ? undefined : json['maxRetries'],
    };
}

export function ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauthToJSON(value?: ApplicationConfigPropertiesKafkaSchemaRegistryAuthOauth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tokenUrl': value.tokenUrl,
        'clientId': value.clientId,
        'clientSecret': value.clientSecret,
        'scopes': value.scopes,
        'tokenCacheEnabled': value.tokenCacheEnabled,
        'tokenRefreshBuffer': value.tokenRefreshBuffer,
        'maxRetries': value.maxRetries,
    };
}

