/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApplicationConfigPropertiesKafkaCache,
    ApplicationConfigPropertiesKafkaCacheFromJSON,
    ApplicationConfigPropertiesKafkaCacheFromJSONTyped,
    ApplicationConfigPropertiesKafkaCacheToJSON,
    ApplicationConfigPropertiesKafkaClusters,
    ApplicationConfigPropertiesKafkaClustersFromJSON,
    ApplicationConfigPropertiesKafkaClustersFromJSONTyped,
    ApplicationConfigPropertiesKafkaClustersToJSON,
    ApplicationConfigPropertiesKafkaPolling,
    ApplicationConfigPropertiesKafkaPollingFromJSON,
    ApplicationConfigPropertiesKafkaPollingFromJSONTyped,
    ApplicationConfigPropertiesKafkaPollingToJSON,
    ClusterMetricsStoreConfig,
    ClusterMetricsStoreConfigFromJSON,
    ClusterMetricsStoreConfigFromJSONTyped,
    ClusterMetricsStoreConfigToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesKafka
 */
export interface ApplicationConfigPropertiesKafka {
    /**
     * 
     * @type {ApplicationConfigPropertiesKafkaPolling}
     * @memberof ApplicationConfigPropertiesKafka
     */
    polling?: ApplicationConfigPropertiesKafkaPolling;
    /**
     * 
     * @type {number}
     * @memberof ApplicationConfigPropertiesKafka
     */
    adminClientTimeout?: number;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafka
     */
    internalTopicPrefix?: string;
    /**
     * 
     * @type {ClusterMetricsStoreConfig}
     * @memberof ApplicationConfigPropertiesKafka
     */
    defaultMetricsStorage?: ClusterMetricsStoreConfig;
    /**
     * 
     * @type {ApplicationConfigPropertiesKafkaCache}
     * @memberof ApplicationConfigPropertiesKafka
     */
    cache?: ApplicationConfigPropertiesKafkaCache;
    /**
     * 
     * @type {Array<ApplicationConfigPropertiesKafkaClusters>}
     * @memberof ApplicationConfigPropertiesKafka
     */
    clusters?: Array<ApplicationConfigPropertiesKafkaClusters>;
}

export function ApplicationConfigPropertiesKafkaFromJSON(json: any): ApplicationConfigPropertiesKafka {
    return ApplicationConfigPropertiesKafkaFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesKafkaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesKafka {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'polling': !exists(json, 'polling') ? undefined : ApplicationConfigPropertiesKafkaPollingFromJSON(json['polling']),
        'adminClientTimeout': !exists(json, 'adminClientTimeout') ? undefined : json['adminClientTimeout'],
        'internalTopicPrefix': !exists(json, 'internalTopicPrefix') ? undefined : json['internalTopicPrefix'],
        'defaultMetricsStorage': !exists(json, 'defaultMetricsStorage') ? undefined : ClusterMetricsStoreConfigFromJSON(json['defaultMetricsStorage']),
        'cache': !exists(json, 'cache') ? undefined : ApplicationConfigPropertiesKafkaCacheFromJSON(json['cache']),
        'clusters': !exists(json, 'clusters') ? undefined : ((json['clusters'] as Array<any>).map(ApplicationConfigPropertiesKafkaClustersFromJSON)),
    };
}

export function ApplicationConfigPropertiesKafkaToJSON(value?: ApplicationConfigPropertiesKafka | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'polling': ApplicationConfigPropertiesKafkaPollingToJSON(value.polling),
        'adminClientTimeout': value.adminClientTimeout,
        'internalTopicPrefix': value.internalTopicPrefix,
        'defaultMetricsStorage': ClusterMetricsStoreConfigToJSON(value.defaultMetricsStorage),
        'cache': ApplicationConfigPropertiesKafkaCacheToJSON(value.cache),
        'clusters': value.clusters === undefined ? undefined : ((value.clusters as Array<any>).map(ApplicationConfigPropertiesKafkaClustersToJSON)),
    };
}

