/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApplicationConfigPropertiesKafkaAudit,
    ApplicationConfigPropertiesKafkaAuditFromJSON,
    ApplicationConfigPropertiesKafkaAuditFromJSONTyped,
    ApplicationConfigPropertiesKafkaAuditToJSON,
    ApplicationConfigPropertiesKafkaKafkaConnect,
    ApplicationConfigPropertiesKafkaKafkaConnectFromJSON,
    ApplicationConfigPropertiesKafkaKafkaConnectFromJSONTyped,
    ApplicationConfigPropertiesKafkaKafkaConnectToJSON,
    ApplicationConfigPropertiesKafkaKsqldbServerAuth,
    ApplicationConfigPropertiesKafkaKsqldbServerAuthFromJSON,
    ApplicationConfigPropertiesKafkaKsqldbServerAuthFromJSONTyped,
    ApplicationConfigPropertiesKafkaKsqldbServerAuthToJSON,
    ApplicationConfigPropertiesKafkaMasking,
    ApplicationConfigPropertiesKafkaMaskingFromJSON,
    ApplicationConfigPropertiesKafkaMaskingFromJSONTyped,
    ApplicationConfigPropertiesKafkaMaskingToJSON,
    ApplicationConfigPropertiesKafkaMetrics,
    ApplicationConfigPropertiesKafkaMetricsFromJSON,
    ApplicationConfigPropertiesKafkaMetricsFromJSONTyped,
    ApplicationConfigPropertiesKafkaMetricsToJSON,
    ApplicationConfigPropertiesKafkaSchemaRegistryAuth,
    ApplicationConfigPropertiesKafkaSchemaRegistryAuthFromJSON,
    ApplicationConfigPropertiesKafkaSchemaRegistryAuthFromJSONTyped,
    ApplicationConfigPropertiesKafkaSchemaRegistryAuthToJSON,
    ApplicationConfigPropertiesKafkaSchemaRegistrySsl,
    ApplicationConfigPropertiesKafkaSchemaRegistrySslFromJSON,
    ApplicationConfigPropertiesKafkaSchemaRegistrySslFromJSONTyped,
    ApplicationConfigPropertiesKafkaSchemaRegistrySslToJSON,
    ApplicationConfigPropertiesKafkaSerde,
    ApplicationConfigPropertiesKafkaSerdeFromJSON,
    ApplicationConfigPropertiesKafkaSerdeFromJSONTyped,
    ApplicationConfigPropertiesKafkaSerdeToJSON,
    ApplicationConfigPropertiesKafkaSsl,
    ApplicationConfigPropertiesKafkaSslFromJSON,
    ApplicationConfigPropertiesKafkaSslFromJSONTyped,
    ApplicationConfigPropertiesKafkaSslToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesKafkaClusters
 */
export interface ApplicationConfigPropertiesKafkaClusters {
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    bootstrapServers?: string;
    /**
     * 
     * @type {ApplicationConfigPropertiesKafkaSsl}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    ssl?: ApplicationConfigPropertiesKafkaSsl;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    schemaRegistry?: string;
    /**
     * 
     * @type {ApplicationConfigPropertiesKafkaSchemaRegistryAuth}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    schemaRegistryAuth?: ApplicationConfigPropertiesKafkaSchemaRegistryAuth;
    /**
     * 
     * @type {ApplicationConfigPropertiesKafkaSchemaRegistrySsl}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    schemaRegistrySsl?: ApplicationConfigPropertiesKafkaSchemaRegistrySsl;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    ksqldbServer?: string;
    /**
     * 
     * @type {ApplicationConfigPropertiesKafkaSchemaRegistrySsl}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    ksqldbServerSsl?: ApplicationConfigPropertiesKafkaSchemaRegistrySsl;
    /**
     * 
     * @type {ApplicationConfigPropertiesKafkaKsqldbServerAuth}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    ksqldbServerAuth?: ApplicationConfigPropertiesKafkaKsqldbServerAuth;
    /**
     * 
     * @type {Array<ApplicationConfigPropertiesKafkaKafkaConnect>}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    kafkaConnect?: Array<ApplicationConfigPropertiesKafkaKafkaConnect>;
    /**
     * 
     * @type {ApplicationConfigPropertiesKafkaMetrics}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    metrics?: ApplicationConfigPropertiesKafkaMetrics;
    /**
     * 
     * @type {{ [key: string]: any | undefined; }}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    properties?: { [key: string]: any | undefined; };
    /**
     * 
     * @type {{ [key: string]: any | undefined; }}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    consumerProperties?: { [key: string]: any | undefined; };
    /**
     * 
     * @type {{ [key: string]: any | undefined; }}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    producerProperties?: { [key: string]: any | undefined; };
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    readOnly?: boolean;
    /**
     * 
     * @type {Array<ApplicationConfigPropertiesKafkaSerde>}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    serde?: Array<ApplicationConfigPropertiesKafkaSerde>;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    defaultKeySerde?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    defaultValueSerde?: string;
    /**
     * 
     * @type {Array<ApplicationConfigPropertiesKafkaMasking>}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    masking?: Array<ApplicationConfigPropertiesKafkaMasking>;
    /**
     * 
     * @type {number}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    pollingThrottleRate?: number;
    /**
     * 
     * @type {ApplicationConfigPropertiesKafkaAudit}
     * @memberof ApplicationConfigPropertiesKafkaClusters
     */
    audit?: ApplicationConfigPropertiesKafkaAudit;
}

export function ApplicationConfigPropertiesKafkaClustersFromJSON(json: any): ApplicationConfigPropertiesKafkaClusters {
    return ApplicationConfigPropertiesKafkaClustersFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesKafkaClustersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesKafkaClusters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'bootstrapServers': !exists(json, 'bootstrapServers') ? undefined : json['bootstrapServers'],
        'ssl': !exists(json, 'ssl') ? undefined : ApplicationConfigPropertiesKafkaSslFromJSON(json['ssl']),
        'schemaRegistry': !exists(json, 'schemaRegistry') ? undefined : json['schemaRegistry'],
        'schemaRegistryAuth': !exists(json, 'schemaRegistryAuth') ? undefined : ApplicationConfigPropertiesKafkaSchemaRegistryAuthFromJSON(json['schemaRegistryAuth']),
        'schemaRegistrySsl': !exists(json, 'schemaRegistrySsl') ? undefined : ApplicationConfigPropertiesKafkaSchemaRegistrySslFromJSON(json['schemaRegistrySsl']),
        'ksqldbServer': !exists(json, 'ksqldbServer') ? undefined : json['ksqldbServer'],
        'ksqldbServerSsl': !exists(json, 'ksqldbServerSsl') ? undefined : ApplicationConfigPropertiesKafkaSchemaRegistrySslFromJSON(json['ksqldbServerSsl']),
        'ksqldbServerAuth': !exists(json, 'ksqldbServerAuth') ? undefined : ApplicationConfigPropertiesKafkaKsqldbServerAuthFromJSON(json['ksqldbServerAuth']),
        'kafkaConnect': !exists(json, 'kafkaConnect') ? undefined : ((json['kafkaConnect'] as Array<any>).map(ApplicationConfigPropertiesKafkaKafkaConnectFromJSON)),
        'metrics': !exists(json, 'metrics') ? undefined : ApplicationConfigPropertiesKafkaMetricsFromJSON(json['metrics']),
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
        'consumerProperties': !exists(json, 'consumerProperties') ? undefined : json['consumerProperties'],
        'producerProperties': !exists(json, 'producerProperties') ? undefined : json['producerProperties'],
        'readOnly': !exists(json, 'readOnly') ? undefined : json['readOnly'],
        'serde': !exists(json, 'serde') ? undefined : ((json['serde'] as Array<any>).map(ApplicationConfigPropertiesKafkaSerdeFromJSON)),
        'defaultKeySerde': !exists(json, 'defaultKeySerde') ? undefined : json['defaultKeySerde'],
        'defaultValueSerde': !exists(json, 'defaultValueSerde') ? undefined : json['defaultValueSerde'],
        'masking': !exists(json, 'masking') ? undefined : ((json['masking'] as Array<any>).map(ApplicationConfigPropertiesKafkaMaskingFromJSON)),
        'pollingThrottleRate': !exists(json, 'pollingThrottleRate') ? undefined : json['pollingThrottleRate'],
        'audit': !exists(json, 'audit') ? undefined : ApplicationConfigPropertiesKafkaAuditFromJSON(json['audit']),
    };
}

export function ApplicationConfigPropertiesKafkaClustersToJSON(value?: ApplicationConfigPropertiesKafkaClusters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'bootstrapServers': value.bootstrapServers,
        'ssl': ApplicationConfigPropertiesKafkaSslToJSON(value.ssl),
        'schemaRegistry': value.schemaRegistry,
        'schemaRegistryAuth': ApplicationConfigPropertiesKafkaSchemaRegistryAuthToJSON(value.schemaRegistryAuth),
        'schemaRegistrySsl': ApplicationConfigPropertiesKafkaSchemaRegistrySslToJSON(value.schemaRegistrySsl),
        'ksqldbServer': value.ksqldbServer,
        'ksqldbServerSsl': ApplicationConfigPropertiesKafkaSchemaRegistrySslToJSON(value.ksqldbServerSsl),
        'ksqldbServerAuth': ApplicationConfigPropertiesKafkaKsqldbServerAuthToJSON(value.ksqldbServerAuth),
        'kafkaConnect': value.kafkaConnect === undefined ? undefined : ((value.kafkaConnect as Array<any>).map(ApplicationConfigPropertiesKafkaKafkaConnectToJSON)),
        'metrics': ApplicationConfigPropertiesKafkaMetricsToJSON(value.metrics),
        'properties': value.properties,
        'consumerProperties': value.consumerProperties,
        'producerProperties': value.producerProperties,
        'readOnly': value.readOnly,
        'serde': value.serde === undefined ? undefined : ((value.serde as Array<any>).map(ApplicationConfigPropertiesKafkaSerdeToJSON)),
        'defaultKeySerde': value.defaultKeySerde,
        'defaultValueSerde': value.defaultValueSerde,
        'masking': value.masking === undefined ? undefined : ((value.masking as Array<any>).map(ApplicationConfigPropertiesKafkaMaskingToJSON)),
        'pollingThrottleRate': value.pollingThrottleRate,
        'audit': ApplicationConfigPropertiesKafkaAuditToJSON(value.audit),
    };
}

