/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApplicationConfigPropertiesAuth,
    ApplicationConfigPropertiesAuthFromJSON,
    ApplicationConfigPropertiesAuthFromJSONTyped,
    ApplicationConfigPropertiesAuthToJSON,
    ApplicationConfigPropertiesKafka,
    ApplicationConfigPropertiesKafkaFromJSON,
    ApplicationConfigPropertiesKafkaFromJSONTyped,
    ApplicationConfigPropertiesKafkaToJSON,
    ApplicationConfigPropertiesRbac,
    ApplicationConfigPropertiesRbacFromJSON,
    ApplicationConfigPropertiesRbacFromJSONTyped,
    ApplicationConfigPropertiesRbacToJSON,
    ApplicationConfigPropertiesWebclient,
    ApplicationConfigPropertiesWebclientFromJSON,
    ApplicationConfigPropertiesWebclientFromJSONTyped,
    ApplicationConfigPropertiesWebclientToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApplicationConfigProperties
 */
export interface ApplicationConfigProperties {
    /**
     * 
     * @type {ApplicationConfigPropertiesAuth}
     * @memberof ApplicationConfigProperties
     */
    auth?: ApplicationConfigPropertiesAuth;
    /**
     * 
     * @type {ApplicationConfigPropertiesRbac}
     * @memberof ApplicationConfigProperties
     */
    rbac?: ApplicationConfigPropertiesRbac;
    /**
     * 
     * @type {ApplicationConfigPropertiesWebclient}
     * @memberof ApplicationConfigProperties
     */
    webclient?: ApplicationConfigPropertiesWebclient;
    /**
     * 
     * @type {ApplicationConfigPropertiesKafka}
     * @memberof ApplicationConfigProperties
     */
    kafka?: ApplicationConfigPropertiesKafka;
}

export function ApplicationConfigPropertiesFromJSON(json: any): ApplicationConfigProperties {
    return ApplicationConfigPropertiesFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'auth': !exists(json, 'auth') ? undefined : ApplicationConfigPropertiesAuthFromJSON(json['auth']),
        'rbac': !exists(json, 'rbac') ? undefined : ApplicationConfigPropertiesRbacFromJSON(json['rbac']),
        'webclient': !exists(json, 'webclient') ? undefined : ApplicationConfigPropertiesWebclientFromJSON(json['webclient']),
        'kafka': !exists(json, 'kafka') ? undefined : ApplicationConfigPropertiesKafkaFromJSON(json['kafka']),
    };
}

export function ApplicationConfigPropertiesToJSON(value?: ApplicationConfigProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'auth': ApplicationConfigPropertiesAuthToJSON(value.auth),
        'rbac': ApplicationConfigPropertiesRbacToJSON(value.rbac),
        'webclient': ApplicationConfigPropertiesWebclientToJSON(value.webclient),
        'kafka': ApplicationConfigPropertiesKafkaToJSON(value.kafka),
    };
}

