/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationConfigPropertiesKafkaAudit
 */
export interface ApplicationConfigPropertiesKafkaAudit {
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaAudit
     */
    level?: ApplicationConfigPropertiesKafkaAuditLevelEnum;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfigPropertiesKafkaAudit
     */
    topic?: string;
    /**
     * 
     * @type {number}
     * @memberof ApplicationConfigPropertiesKafkaAudit
     */
    auditTopicsPartitions?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationConfigPropertiesKafkaAudit
     */
    topicAuditEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationConfigPropertiesKafkaAudit
     */
    consoleAuditEnabled?: boolean;
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof ApplicationConfigPropertiesKafkaAudit
     */
    auditTopicProperties?: { [key: string]: string | undefined; };
}

/**
* @export
* @enum {string}
*/
export enum ApplicationConfigPropertiesKafkaAuditLevelEnum {
    ALL = 'ALL',
    ALTER_ONLY = 'ALTER_ONLY'
}

export function ApplicationConfigPropertiesKafkaAuditFromJSON(json: any): ApplicationConfigPropertiesKafkaAudit {
    return ApplicationConfigPropertiesKafkaAuditFromJSONTyped(json, false);
}

export function ApplicationConfigPropertiesKafkaAuditFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigPropertiesKafkaAudit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'level': !exists(json, 'level') ? undefined : json['level'],
        'topic': !exists(json, 'topic') ? undefined : json['topic'],
        'auditTopicsPartitions': !exists(json, 'auditTopicsPartitions') ? undefined : json['auditTopicsPartitions'],
        'topicAuditEnabled': !exists(json, 'topicAuditEnabled') ? undefined : json['topicAuditEnabled'],
        'consoleAuditEnabled': !exists(json, 'consoleAuditEnabled') ? undefined : json['consoleAuditEnabled'],
        'auditTopicProperties': !exists(json, 'auditTopicProperties') ? undefined : json['auditTopicProperties'],
    };
}

export function ApplicationConfigPropertiesKafkaAuditToJSON(value?: ApplicationConfigPropertiesKafkaAudit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'level': value.level,
        'topic': value.topic,
        'auditTopicsPartitions': value.auditTopicsPartitions,
        'topicAuditEnabled': value.topicAuditEnabled,
        'consoleAuditEnabled': value.consoleAuditEnabled,
        'auditTopicProperties': value.auditTopicProperties,
    };
}

