/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserInfo,
    UserInfoFromJSON,
    UserInfoFromJSONTyped,
    UserInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface AuthenticationInfo
 */
export interface AuthenticationInfo {
    /**
     * true if role based access control is enabled and granular permission access is required
     * @type {boolean}
     * @memberof AuthenticationInfo
     */
    rbacEnabled: boolean;
    /**
     * 
     * @type {UserInfo}
     * @memberof AuthenticationInfo
     */
    userInfo?: UserInfo;
}

export function AuthenticationInfoFromJSON(json: any): AuthenticationInfo {
    return AuthenticationInfoFromJSONTyped(json, false);
}

export function AuthenticationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rbacEnabled': json['rbacEnabled'],
        'userInfo': !exists(json, 'userInfo') ? undefined : UserInfoFromJSON(json['userInfo']),
    };
}

export function AuthenticationInfoToJSON(value?: AuthenticationInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rbacEnabled': value.rbacEnabled,
        'userInfo': UserInfoToJSON(value.userInfo),
    };
}

