/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TopicLogdirs,
    TopicLogdirsFromJSON,
    TopicLogdirsFromJSONTyped,
    TopicLogdirsToJSON,
} from './';

/**
 * 
 * @export
 * @interface BrokerLogdirs
 */
export interface BrokerLogdirs {
    /**
     * 
     * @type {string}
     * @memberof BrokerLogdirs
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BrokerLogdirs
     */
    error?: string;
    /**
     * 
     * @type {Array<TopicLogdirs>}
     * @memberof BrokerLogdirs
     */
    topics?: Array<TopicLogdirs>;
}

export function BrokerLogdirsFromJSON(json: any): BrokerLogdirs {
    return BrokerLogdirsFromJSONTyped(json, false);
}

export function BrokerLogdirsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrokerLogdirs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'error': !exists(json, 'error') ? undefined : json['error'],
        'topics': !exists(json, 'topics') ? undefined : ((json['topics'] as Array<any>).map(TopicLogdirsFromJSON)),
    };
}

export function BrokerLogdirsToJSON(value?: BrokerLogdirs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'error': value.error,
        'topics': value.topics === undefined ? undefined : ((value.topics as Array<any>).map(TopicLogdirsToJSON)),
    };
}

