/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApplicationPropertyValidation,
    ApplicationPropertyValidationFromJSON,
    ApplicationPropertyValidationFromJSONTyped,
    ApplicationPropertyValidationToJSON,
} from './';

/**
 * 
 * @export
 * @interface ClusterConfigValidation
 */
export interface ClusterConfigValidation {
    /**
     * 
     * @type {ApplicationPropertyValidation}
     * @memberof ClusterConfigValidation
     */
    kafka: ApplicationPropertyValidation;
    /**
     * 
     * @type {ApplicationPropertyValidation}
     * @memberof ClusterConfigValidation
     */
    schemaRegistry?: ApplicationPropertyValidation;
    /**
     * 
     * @type {{ [key: string]: ApplicationPropertyValidation | undefined; }}
     * @memberof ClusterConfigValidation
     */
    kafkaConnects?: { [key: string]: ApplicationPropertyValidation | undefined; };
    /**
     * 
     * @type {ApplicationPropertyValidation}
     * @memberof ClusterConfigValidation
     */
    ksqldb?: ApplicationPropertyValidation;
    /**
     * 
     * @type {ApplicationPropertyValidation}
     * @memberof ClusterConfigValidation
     */
    prometheusStorage?: ApplicationPropertyValidation;
}

export function ClusterConfigValidationFromJSON(json: any): ClusterConfigValidation {
    return ClusterConfigValidationFromJSONTyped(json, false);
}

export function ClusterConfigValidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterConfigValidation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kafka': ApplicationPropertyValidationFromJSON(json['kafka']),
        'schemaRegistry': !exists(json, 'schemaRegistry') ? undefined : ApplicationPropertyValidationFromJSON(json['schemaRegistry']),
        'kafkaConnects': !exists(json, 'kafkaConnects') ? undefined : (mapValues(json['kafkaConnects'], ApplicationPropertyValidationFromJSON)),
        'ksqldb': !exists(json, 'ksqldb') ? undefined : ApplicationPropertyValidationFromJSON(json['ksqldb']),
        'prometheusStorage': !exists(json, 'prometheusStorage') ? undefined : ApplicationPropertyValidationFromJSON(json['prometheusStorage']),
    };
}

export function ClusterConfigValidationToJSON(value?: ClusterConfigValidation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kafka': ApplicationPropertyValidationToJSON(value.kafka),
        'schemaRegistry': ApplicationPropertyValidationToJSON(value.schemaRegistry),
        'kafkaConnects': value.kafkaConnects === undefined ? undefined : (mapValues(value.kafkaConnects, ApplicationPropertyValidationToJSON)),
        'ksqldb': ApplicationPropertyValidationToJSON(value.ksqldb),
        'prometheusStorage': ApplicationPropertyValidationToJSON(value.prometheusStorage),
    };
}

