/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Metric,
    MetricFromJSON,
    MetricFromJSONTyped,
    MetricToJSON,
} from './';

/**
 * 
 * @export
 * @interface ClusterMetrics
 */
export interface ClusterMetrics {
    /**
     * 
     * @type {Array<Metric>}
     * @memberof ClusterMetrics
     */
    items: Array<Metric>;
}

export function ClusterMetricsFromJSON(json: any): ClusterMetrics {
    return ClusterMetricsFromJSONTyped(json, false);
}

export function ClusterMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterMetrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(MetricFromJSON)),
    };
}

export function ClusterMetricsToJSON(value?: ClusterMetrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(MetricToJSON)),
    };
}

