/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompatibilityCheckResponse
 */
export interface CompatibilityCheckResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CompatibilityCheckResponse
     */
    isCompatible: boolean;
}

export function CompatibilityCheckResponseFromJSON(json: any): CompatibilityCheckResponse {
    return CompatibilityCheckResponseFromJSONTyped(json, false);
}

export function CompatibilityCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompatibilityCheckResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isCompatible': json['isCompatible'],
    };
}

export function CompatibilityCheckResponseToJSON(value?: CompatibilityCheckResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isCompatible': value.isCompatible,
    };
}

