/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ConnectorColumnsToSort {
    NAME = 'NAME',
    CONNECT = 'CONNECT',
    TYPE = 'TYPE',
    STATUS = 'STATUS'
}

export function ConnectorColumnsToSortFromJSON(json: any): ConnectorColumnsToSort {
    return ConnectorColumnsToSortFromJSONTyped(json, false);
}

export function ConnectorColumnsToSortFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorColumnsToSort {
    return json as ConnectorColumnsToSort;
}

export function ConnectorColumnsToSortToJSON(value?: ConnectorColumnsToSort | null): any {
    return value as any;
}

