/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectorPluginConfigValue
 */
export interface ConnectorPluginConfigValue {
    /**
     * 
     * @type {string}
     * @memberof ConnectorPluginConfigValue
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorPluginConfigValue
     */
    value?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConnectorPluginConfigValue
     */
    recommendedValues?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConnectorPluginConfigValue
     */
    errors?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ConnectorPluginConfigValue
     */
    visible?: boolean;
}

export function ConnectorPluginConfigValueFromJSON(json: any): ConnectorPluginConfigValue {
    return ConnectorPluginConfigValueFromJSONTyped(json, false);
}

export function ConnectorPluginConfigValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorPluginConfigValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'recommendedValues': !exists(json, 'recommendedValues') ? undefined : json['recommendedValues'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
        'visible': !exists(json, 'visible') ? undefined : json['visible'],
    };
}

export function ConnectorPluginConfigValueToJSON(value?: ConnectorPluginConfigValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': value.value,
        'recommendedValues': value.recommendedValues,
        'errors': value.errors,
        'visible': value.visible,
    };
}

