/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ConnectorState {
    RUNNING = 'RUNNING',
    FAILED = 'FAILED',
    PAUSED = 'PAUSED',
    UNASSIGNED = 'UNASSIGNED',
    TASK_FAILED = 'TASK_FAILED',
    RESTARTING = 'RESTARTING',
    STOPPED = 'STOPPED'
}

export function ConnectorStateFromJSON(json: any): ConnectorState {
    return ConnectorStateFromJSONTyped(json, false);
}

export function ConnectorStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorState {
    return json as ConnectorState;
}

export function ConnectorStateToJSON(value?: ConnectorState | null): any {
    return value as any;
}

