/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Connect
 */
export interface Connect {
    /**
     * 
     * @type {string}
     * @memberof Connect
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Connect
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof Connect
     */
    connectorsCount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Connect
     */
    failedConnectorsCount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Connect
     */
    tasksCount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Connect
     */
    failedTasksCount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Connect
     */
    version?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Connect
     */
    commit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Connect
     */
    clusterId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Connect
     */
    consumerNamePattern?: string;
}

export function ConnectFromJSON(json: any): Connect {
    return ConnectFromJSONTyped(json, false);
}

export function ConnectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Connect {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'connectorsCount': !exists(json, 'connectorsCount') ? undefined : json['connectorsCount'],
        'failedConnectorsCount': !exists(json, 'failedConnectorsCount') ? undefined : json['failedConnectorsCount'],
        'tasksCount': !exists(json, 'tasksCount') ? undefined : json['tasksCount'],
        'failedTasksCount': !exists(json, 'failedTasksCount') ? undefined : json['failedTasksCount'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'commit': !exists(json, 'commit') ? undefined : json['commit'],
        'clusterId': !exists(json, 'clusterId') ? undefined : json['clusterId'],
        'consumerNamePattern': !exists(json, 'consumerNamePattern') ? undefined : json['consumerNamePattern'],
    };
}

export function ConnectToJSON(value?: Connect | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'address': value.address,
        'connectorsCount': value.connectorsCount,
        'failedConnectorsCount': value.failedConnectorsCount,
        'tasksCount': value.tasksCount,
        'failedTasksCount': value.failedTasksCount,
        'version': value.version,
        'commit': value.commit,
        'clusterId': value.clusterId,
        'consumerNamePattern': value.consumerNamePattern,
    };
}

