/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Broker,
    BrokerFromJSON,
    BrokerFromJSONTyped,
    BrokerToJSON,
    ConsumerGroup,
    ConsumerGroupFromJSON,
    ConsumerGroupFromJSONTyped,
    ConsumerGroupToJSON,
    ConsumerGroupState,
    ConsumerGroupStateFromJSON,
    ConsumerGroupStateFromJSONTyped,
    ConsumerGroupStateToJSON,
    ConsumerGroupTopicPartition,
    ConsumerGroupTopicPartitionFromJSON,
    ConsumerGroupTopicPartitionFromJSONTyped,
    ConsumerGroupTopicPartitionToJSON,
} from './';

/**
 * 
 * @export
 * @interface ConsumerGroupDetails
 */
export interface ConsumerGroupDetails extends ConsumerGroup {
    /**
     * 
     * @type {Array<ConsumerGroupTopicPartition>}
     * @memberof ConsumerGroupDetails
     */
    partitions?: Array<ConsumerGroupTopicPartition>;
}

export function ConsumerGroupDetailsFromJSON(json: any): ConsumerGroupDetails {
    return ConsumerGroupDetailsFromJSONTyped(json, false);
}

export function ConsumerGroupDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsumerGroupDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ConsumerGroupFromJSONTyped(json, ignoreDiscriminator),
        'partitions': !exists(json, 'partitions') ? undefined : ((json['partitions'] as Array<any>).map(ConsumerGroupTopicPartitionFromJSON)),
    };
}

export function ConsumerGroupDetailsToJSON(value?: ConsumerGroupDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ConsumerGroupToJSON(value),
        'partitions': value.partitions === undefined ? undefined : ((value.partitions as Array<any>).map(ConsumerGroupTopicPartitionToJSON)),
    };
}

