/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConsumerGroupLag,
    ConsumerGroupLagFromJSON,
    ConsumerGroupLagFromJSONTyped,
    ConsumerGroupLagToJSON,
} from './';

/**
 * 
 * @export
 * @interface ConsumerGroupsLagResponse
 */
export interface ConsumerGroupsLagResponse {
    /**
     * 
     * @type {number}
     * @memberof ConsumerGroupsLagResponse
     */
    updateTimestamp: number;
    /**
     * 
     * @type {{ [key: string]: ConsumerGroupLag | undefined; }}
     * @memberof ConsumerGroupsLagResponse
     */
    consumerGroups: { [key: string]: ConsumerGroupLag | undefined; };
}

export function ConsumerGroupsLagResponseFromJSON(json: any): ConsumerGroupsLagResponse {
    return ConsumerGroupsLagResponseFromJSONTyped(json, false);
}

export function ConsumerGroupsLagResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsumerGroupsLagResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'updateTimestamp': json['updateTimestamp'],
        'consumerGroups': (mapValues(json['consumerGroups'], ConsumerGroupLagFromJSON)),
    };
}

export function ConsumerGroupsLagResponseToJSON(value?: ConsumerGroupsLagResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'updateTimestamp': value.updateTimestamp,
        'consumerGroups': (mapValues(value.consumerGroups, ConsumerGroupLagToJSON)),
    };
}

