/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ControllerType {
    ZOOKEEPER = 'ZOOKEEPER',
    KRAFT = 'KRAFT'
}

export function ControllerTypeFromJSON(json: any): ControllerType {
    return ControllerTypeFromJSONTyped(json, false);
}

export function ControllerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllerType {
    return json as ControllerType;
}

export function ControllerTypeToJSON(value?: ControllerType | null): any {
    return value as any;
}

