/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GraphDataRequest
 */
export interface GraphDataRequest {
    /**
     * 
     * @type {string}
     * @memberof GraphDataRequest
     */
    id?: string;
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof GraphDataRequest
     */
    parameters?: { [key: string]: string | undefined; };
    /**
     * 
     * @type {Date}
     * @memberof GraphDataRequest
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GraphDataRequest
     */
    to?: Date;
}

export function GraphDataRequestFromJSON(json: any): GraphDataRequest {
    return GraphDataRequestFromJSONTyped(json, false);
}

export function GraphDataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphDataRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'parameters': !exists(json, 'parameters') ? undefined : json['parameters'],
        'from': !exists(json, 'from') ? undefined : (new Date(json['from'])),
        'to': !exists(json, 'to') ? undefined : (new Date(json['to'])),
    };
}

export function GraphDataRequestToJSON(value?: GraphDataRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'parameters': value.parameters,
        'from': value.from === undefined ? undefined : (value.from.toISOString()),
        'to': value.to === undefined ? undefined : (value.to.toISOString()),
    };
}

