/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GraphDescription,
    GraphDescriptionFromJSON,
    GraphDescriptionFromJSONTyped,
    GraphDescriptionToJSON,
} from './';

/**
 * 
 * @export
 * @interface GraphDescriptions
 */
export interface GraphDescriptions {
    /**
     * 
     * @type {Array<GraphDescription>}
     * @memberof GraphDescriptions
     */
    graphs?: Array<GraphDescription>;
}

export function GraphDescriptionsFromJSON(json: any): GraphDescriptions {
    return GraphDescriptionsFromJSONTyped(json, false);
}

export function GraphDescriptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphDescriptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'graphs': !exists(json, 'graphs') ? undefined : ((json['graphs'] as Array<any>).map(GraphDescriptionFromJSON)),
    };
}

export function GraphDescriptionsToJSON(value?: GraphDescriptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'graphs': value.graphs === undefined ? undefined : ((value.graphs as Array<any>).map(GraphDescriptionToJSON)),
    };
}

