/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum KafkaAclNamePatternType {
    MATCH = 'MATCH',
    LITERAL = 'LITERAL',
    PREFIXED = 'PREFIXED'
}

export function KafkaAclNamePatternTypeFromJSON(json: any): KafkaAclNamePatternType {
    return KafkaAclNamePatternTypeFromJSONTyped(json, false);
}

export function KafkaAclNamePatternTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): KafkaAclNamePatternType {
    return json as KafkaAclNamePatternType;
}

export function KafkaAclNamePatternTypeToJSON(value?: KafkaAclNamePatternType | null): any {
    return value as any;
}

