/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KsqlCommandV2Response
 */
export interface KsqlCommandV2Response {
    /**
     * 
     * @type {string}
     * @memberof KsqlCommandV2Response
     */
    pipeId: string;
}

export function KsqlCommandV2ResponseFromJSON(json: any): KsqlCommandV2Response {
    return KsqlCommandV2ResponseFromJSONTyped(json, false);
}

export function KsqlCommandV2ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KsqlCommandV2Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pipeId': json['pipeId'],
    };
}

export function KsqlCommandV2ResponseToJSON(value?: KsqlCommandV2Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pipeId': value.pipeId,
    };
}

