/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KsqlTableDescription
 */
export interface KsqlTableDescription {
    /**
     * 
     * @type {string}
     * @memberof KsqlTableDescription
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof KsqlTableDescription
     */
    topic?: string;
    /**
     * 
     * @type {string}
     * @memberof KsqlTableDescription
     */
    keyFormat?: string;
    /**
     * 
     * @type {string}
     * @memberof KsqlTableDescription
     */
    valueFormat?: string;
    /**
     * 
     * @type {boolean}
     * @memberof KsqlTableDescription
     */
    isWindowed?: boolean;
}

export function KsqlTableDescriptionFromJSON(json: any): KsqlTableDescription {
    return KsqlTableDescriptionFromJSONTyped(json, false);
}

export function KsqlTableDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): KsqlTableDescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'topic': !exists(json, 'topic') ? undefined : json['topic'],
        'keyFormat': !exists(json, 'keyFormat') ? undefined : json['keyFormat'],
        'valueFormat': !exists(json, 'valueFormat') ? undefined : json['valueFormat'],
        'isWindowed': !exists(json, 'isWindowed') ? undefined : json['isWindowed'],
    };
}

export function KsqlTableDescriptionToJSON(value?: KsqlTableDescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'topic': value.topic,
        'keyFormat': value.keyFormat,
        'valueFormat': value.valueFormat,
        'isWindowed': value.isWindowed,
    };
}

