/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageFilterRegistration
 */
export interface MessageFilterRegistration {
    /**
     * 
     * @type {string}
     * @memberof MessageFilterRegistration
     */
    filterCode?: string;
}

export function MessageFilterRegistrationFromJSON(json: any): MessageFilterRegistration {
    return MessageFilterRegistrationFromJSONTyped(json, false);
}

export function MessageFilterRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageFilterRegistration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'filterCode': !exists(json, 'filterCode') ? undefined : json['filterCode'],
    };
}

export function MessageFilterRegistrationToJSON(value?: MessageFilterRegistration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'filterCode': value.filterCode,
    };
}

