/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SchemaReference,
    SchemaReferenceFromJSON,
    SchemaReferenceFromJSONTyped,
    SchemaReferenceToJSON,
    SchemaType,
    SchemaTypeFromJSON,
    SchemaTypeFromJSONTyped,
    SchemaTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface NewSchemaSubject
 */
export interface NewSchemaSubject {
    /**
     * should be set for creating/updating schema subject
     * @type {string}
     * @memberof NewSchemaSubject
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof NewSchemaSubject
     */
    schema: string;
    /**
     * 
     * @type {SchemaType}
     * @memberof NewSchemaSubject
     */
    schemaType: SchemaType;
    /**
     * 
     * @type {Array<SchemaReference>}
     * @memberof NewSchemaSubject
     */
    references?: Array<SchemaReference>;
}

export function NewSchemaSubjectFromJSON(json: any): NewSchemaSubject {
    return NewSchemaSubjectFromJSONTyped(json, false);
}

export function NewSchemaSubjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewSchemaSubject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subject': json['subject'],
        'schema': json['schema'],
        'schemaType': SchemaTypeFromJSON(json['schemaType']),
        'references': !exists(json, 'references') ? undefined : ((json['references'] as Array<any>).map(SchemaReferenceFromJSON)),
    };
}

export function NewSchemaSubjectToJSON(value?: NewSchemaSubject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subject': value.subject,
        'schema': value.schema,
        'schemaType': SchemaTypeToJSON(value.schemaType),
        'references': value.references === undefined ? undefined : ((value.references as Array<any>).map(SchemaReferenceToJSON)),
    };
}

