/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuthProvider
 */
export interface OAuthProvider {
    /**
     * 
     * @type {string}
     * @memberof OAuthProvider
     */
    clientName: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthProvider
     */
    authorizationUri: string;
}

export function OAuthProviderFromJSON(json: any): OAuthProvider {
    return OAuthProviderFromJSONTyped(json, false);
}

export function OAuthProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthProvider {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientName': json['clientName'],
        'authorizationUri': json['authorizationUri'],
    };
}

export function OAuthProviderToJSON(value?: OAuthProvider | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clientName': value.clientName,
        'authorizationUri': value.authorizationUri,
    };
}

