/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PollingMode {
    FROM_OFFSET = 'FROM_OFFSET',
    TO_OFFSET = 'TO_OFFSET',
    FROM_TIMESTAMP = 'FROM_TIMESTAMP',
    TO_TIMESTAMP = 'TO_TIMESTAMP',
    LATEST = 'LATEST',
    EARLIEST = 'EARLIEST',
    TAILING = 'TAILING'
}

export function PollingModeFromJSON(json: any): PollingMode {
    return PollingModeFromJSONTyped(json, false);
}

export function PollingModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PollingMode {
    return json as PollingMode;
}

export function PollingModeToJSON(value?: PollingMode | null): any {
    return value as any;
}

