/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PrometheusApiBaseResponse,
    PrometheusApiBaseResponseFromJSON,
    PrometheusApiBaseResponseFromJSONTyped,
    PrometheusApiBaseResponseToJSON,
    PrometheusApiQueryResponseData,
    PrometheusApiQueryResponseDataFromJSON,
    PrometheusApiQueryResponseDataFromJSONTyped,
    PrometheusApiQueryResponseDataToJSON,
} from './';

/**
 * 
 * @export
 * @interface PrometheusApiQueryResponse
 */
export interface PrometheusApiQueryResponse {
    /**
     * 
     * @type {PrometheusApiQueryResponseData}
     * @memberof PrometheusApiQueryResponse
     */
    data?: PrometheusApiQueryResponseData;
    /**
     * 
     * @type {string}
     * @memberof PrometheusApiQueryResponse
     */
    status: PrometheusApiQueryResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PrometheusApiQueryResponse
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof PrometheusApiQueryResponse
     */
    errorType?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PrometheusApiQueryResponse
     */
    warnings?: Array<string>;
}

/**
* @export
* @enum {string}
*/
export enum PrometheusApiQueryResponseStatusEnum {
    SUCCESS = 'success',
    ERROR = 'error'
}

export function PrometheusApiQueryResponseFromJSON(json: any): PrometheusApiQueryResponse {
    return PrometheusApiQueryResponseFromJSONTyped(json, false);
}

export function PrometheusApiQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrometheusApiQueryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : PrometheusApiQueryResponseDataFromJSON(json['data']),
        'status': json['status'],
        'error': !exists(json, 'error') ? undefined : json['error'],
        'errorType': !exists(json, 'errorType') ? undefined : json['errorType'],
        'warnings': !exists(json, 'warnings') ? undefined : json['warnings'],
    };
}

export function PrometheusApiQueryResponseToJSON(value?: PrometheusApiQueryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': PrometheusApiQueryResponseDataToJSON(value.data),
        'status': value.status,
        'error': value.error,
        'errorType': value.errorType,
        'warnings': value.warnings,
    };
}

