/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrometheusStorage
 */
export interface PrometheusStorage {
    /**
     * 
     * @type {string}
     * @memberof PrometheusStorage
     */
    url?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PrometheusStorage
     */
    remoteWrite?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PrometheusStorage
     */
    pushGatewayUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PrometheusStorage
     */
    pushGatewayUsername?: string;
    /**
     * 
     * @type {string}
     * @memberof PrometheusStorage
     */
    pushGatewayPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof PrometheusStorage
     */
    pushGatewayJobName?: string;
}

export function PrometheusStorageFromJSON(json: any): PrometheusStorage {
    return PrometheusStorageFromJSONTyped(json, false);
}

export function PrometheusStorageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrometheusStorage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'remoteWrite': !exists(json, 'remoteWrite') ? undefined : json['remoteWrite'],
        'pushGatewayUrl': !exists(json, 'pushGatewayUrl') ? undefined : json['pushGatewayUrl'],
        'pushGatewayUsername': !exists(json, 'pushGatewayUsername') ? undefined : json['pushGatewayUsername'],
        'pushGatewayPassword': !exists(json, 'pushGatewayPassword') ? undefined : json['pushGatewayPassword'],
        'pushGatewayJobName': !exists(json, 'pushGatewayJobName') ? undefined : json['pushGatewayJobName'],
    };
}

export function PrometheusStorageToJSON(value?: PrometheusStorage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'remoteWrite': value.remoteWrite,
        'pushGatewayUrl': value.pushGatewayUrl,
        'pushGatewayUsername': value.pushGatewayUsername,
        'pushGatewayPassword': value.pushGatewayPassword,
        'pushGatewayJobName': value.pushGatewayJobName,
    };
}

