/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrometheusApiQueryResponseData
 */
export interface PrometheusApiQueryResponseData {
    /**
     * 
     * @type {string}
     * @memberof PrometheusApiQueryResponseData
     */
    resultType: PrometheusApiQueryResponseDataResultTypeEnum;
    /**
     *         Depending on resultType format can vary:
     *         "vector":
     *           [
     *             {
     *               "metric": { "<label_name>": "<label_value>", ... },
     *               "value": [ <unix_time>, "<sample_value>" ],
     *               "histogram": [ <unix_time>, <histogram> ]
     *            }, ...
     *           ]
     *         "matrix":
     *           [
     *             {
     *               "metric": { "<label_name>": "<label_value>", ... },
     *               "values": [ [ <unix_time>, "<sample_value>" ], ... ],
     *               "histograms": [ [ <unix_time>, <histogram> ], ... ]
     *             }, ...
     *           ]
     *         "scalar":
     *           [ <unix_time>, "<scalar_value>" ]
     *         "string":
     *           [ <unix_time>, "<string_value>" ]
     * @type {Array<any>}
     * @memberof PrometheusApiQueryResponseData
     */
    result?: Array<any>;
}

/**
* @export
* @enum {string}
*/
export enum PrometheusApiQueryResponseDataResultTypeEnum {
    MATRIX = 'matrix',
    VECTOR = 'vector',
    SCALAR = 'scalar',
    STRING = 'string'
}

export function PrometheusApiQueryResponseDataFromJSON(json: any): PrometheusApiQueryResponseData {
    return PrometheusApiQueryResponseDataFromJSONTyped(json, false);
}

export function PrometheusApiQueryResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrometheusApiQueryResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resultType': json['resultType'],
        'result': !exists(json, 'result') ? undefined : json['result'],
    };
}

export function PrometheusApiQueryResponseDataToJSON(value?: PrometheusApiQueryResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resultType': value.resultType,
        'result': value.result,
    };
}

