/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReplicationFactorChange
 */
export interface ReplicationFactorChange {
    /**
     * 
     * @type {number}
     * @memberof ReplicationFactorChange
     */
    totalReplicationFactor?: number;
}

export function ReplicationFactorChangeFromJSON(json: any): ReplicationFactorChange {
    return ReplicationFactorChangeFromJSONTyped(json, false);
}

export function ReplicationFactorChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplicationFactorChange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalReplicationFactor': !exists(json, 'totalReplicationFactor') ? undefined : json['totalReplicationFactor'],
    };
}

export function ReplicationFactorChangeToJSON(value?: ReplicationFactorChange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalReplicationFactor': value.totalReplicationFactor,
    };
}

