/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ResourceType {
    APPLICATIONCONFIG = 'APPLICATIONCONFIG',
    CLUSTERCONFIG = 'CLUSTERCONFIG',
    TOPIC = 'TOPIC',
    CONSUMER = 'CONSUMER',
    SCHEMA = 'SCHEMA',
    CONNECT = 'CONNECT',
    CONNECTOR = 'CONNECTOR',
    KSQL = 'KSQL',
    ACL = 'ACL',
    AUDIT = 'AUDIT',
    CLIENT_QUOTAS = 'CLIENT_QUOTAS'
}

export function ResourceTypeFromJSON(json: any): ResourceType {
    return ResourceTypeFromJSONTyped(json, false);
}

export function ResourceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceType {
    return json as ResourceType;
}

export function ResourceTypeToJSON(value?: ResourceType | null): any {
    return value as any;
}

