/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApplicationConfig,
    ApplicationConfigFromJSON,
    ApplicationConfigFromJSONTyped,
    ApplicationConfigToJSON,
} from './';

/**
 * 
 * @export
 * @interface RestartRequest
 */
export interface RestartRequest {
    /**
     * 
     * @type {ApplicationConfig}
     * @memberof RestartRequest
     */
    config?: ApplicationConfig;
}

export function RestartRequestFromJSON(json: any): RestartRequest {
    return RestartRequestFromJSONTyped(json, false);
}

export function RestartRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestartRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'config': !exists(json, 'config') ? undefined : ApplicationConfigFromJSON(json['config']),
    };
}

export function RestartRequestToJSON(value?: RestartRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'config': ApplicationConfigToJSON(value.config),
    };
}

