/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SchemaType {
    AVRO = 'AVRO',
    JSON = 'JSON',
    PROTOBUF = 'PROTOBUF'
}

export function SchemaTypeFromJSON(json: any): SchemaType {
    return SchemaTypeFromJSONTyped(json, false);
}

export function SchemaTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaType {
    return json as SchemaType;
}

export function SchemaTypeToJSON(value?: SchemaType | null): any {
    return value as any;
}

