/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SchemaReference,
    SchemaReferenceFromJSON,
    SchemaReferenceFromJSONTyped,
    SchemaReferenceToJSON,
    SchemaType,
    SchemaTypeFromJSON,
    SchemaTypeFromJSONTyped,
    SchemaTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface SchemaSubject
 */
export interface SchemaSubject {
    /**
     * 
     * @type {number}
     * @memberof SchemaSubject
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SchemaSubject
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaSubject
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaSubject
     */
    schema: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaSubject
     */
    compatibilityLevel: string;
    /**
     * 
     * @type {SchemaType}
     * @memberof SchemaSubject
     */
    schemaType: SchemaType;
    /**
     * 
     * @type {Array<SchemaReference>}
     * @memberof SchemaSubject
     */
    references?: Array<SchemaReference>;
    /**
     * 
     * @type {string}
     * @memberof SchemaSubject
     */
    topic?: string | null;
}

export function SchemaSubjectFromJSON(json: any): SchemaSubject {
    return SchemaSubjectFromJSONTyped(json, false);
}

export function SchemaSubjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaSubject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'subject': json['subject'],
        'version': json['version'],
        'schema': json['schema'],
        'compatibilityLevel': json['compatibilityLevel'],
        'schemaType': SchemaTypeFromJSON(json['schemaType']),
        'references': !exists(json, 'references') ? undefined : ((json['references'] as Array<any>).map(SchemaReferenceFromJSON)),
        'topic': !exists(json, 'topic') ? undefined : json['topic'],
    };
}

export function SchemaSubjectToJSON(value?: SchemaSubject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'subject': value.subject,
        'version': value.version,
        'schema': value.schema,
        'compatibilityLevel': value.compatibilityLevel,
        'schemaType': SchemaTypeToJSON(value.schemaType),
        'references': value.references === undefined ? undefined : ((value.references as Array<any>).map(SchemaReferenceToJSON)),
        'topic': value.topic,
    };
}

