/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemaRegistryDeserializeProperties
 */
export interface SchemaRegistryDeserializeProperties {
    /**
     * 
     * @type {string}
     * @memberof SchemaRegistryDeserializeProperties
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof SchemaRegistryDeserializeProperties
     */
    id: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof SchemaRegistryDeserializeProperties
     */
    subjects?: Array<string>;
}

export function SchemaRegistryDeserializePropertiesFromJSON(json: any): SchemaRegistryDeserializeProperties {
    return SchemaRegistryDeserializePropertiesFromJSONTyped(json, false);
}

export function SchemaRegistryDeserializePropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaRegistryDeserializeProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'subjects': !exists(json, 'subjects') ? undefined : json['subjects'],
    };
}

export function SchemaRegistryDeserializePropertiesToJSON(value?: SchemaRegistryDeserializeProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'subjects': value.subjects,
    };
}

