/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SchemaColumnsToSort {
    SUBJECT = 'SUBJECT',
    ID = 'ID',
    TYPE = 'TYPE',
    COMPATIBILITY = 'COMPATIBILITY',
    VERSION = 'VERSION'
}

export function SchemaColumnsToSortFromJSON(json: any): SchemaColumnsToSort {
    return SchemaColumnsToSortFromJSONTyped(json, false);
}

export function SchemaColumnsToSortFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaColumnsToSort {
    return json as SchemaColumnsToSort;
}

export function SchemaColumnsToSortToJSON(value?: SchemaColumnsToSort | null): any {
    return value as any;
}

