/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SeekDirection {
    FORWARD = 'FORWARD',
    BACKWARD = 'BACKWARD',
    TAILING = 'TAILING'
}

export function SeekDirectionFromJSON(json: any): SeekDirection {
    return SeekDirectionFromJSONTyped(json, false);
}

export function SeekDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeekDirection {
    return json as SeekDirection;
}

export function SeekDirectionToJSON(value?: SeekDirection | null): any {
    return value as any;
}

