/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SerdeParameter,
    SerdeParameterFromJSON,
    SerdeParameterFromJSONTyped,
    SerdeParameterToJSON,
} from './';

/**
 * 
 * @export
 * @interface SerdeDescription
 */
export interface SerdeDescription {
    /**
     * 
     * @type {string}
     * @memberof SerdeDescription
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SerdeDescription
     */
    description?: string;
    /**
     * This serde was automatically chosen by cluster config. This should be enabled in UI by default. Also it will be used for deserialization if no serdes passed.
     * @type {boolean}
     * @memberof SerdeDescription
     */
    preferred?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SerdeDescription
     */
    schema?: string;
    /**
     * 
     * @type {{ [key: string]: any | undefined; }}
     * @memberof SerdeDescription
     */
    additionalProperties?: { [key: string]: any | undefined; };
    /**
     * 
     * @type {Array<SerdeParameter>}
     * @memberof SerdeDescription
     */
    parameters?: Array<SerdeParameter>;
}

export function SerdeDescriptionFromJSON(json: any): SerdeDescription {
    return SerdeDescriptionFromJSONTyped(json, false);
}

export function SerdeDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SerdeDescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'preferred': !exists(json, 'preferred') ? undefined : json['preferred'],
        'schema': !exists(json, 'schema') ? undefined : json['schema'],
        'additionalProperties': !exists(json, 'additionalProperties') ? undefined : json['additionalProperties'],
        'parameters': !exists(json, 'parameters') ? undefined : ((json['parameters'] as Array<any>).map(SerdeParameterFromJSON)),
    };
}

export function SerdeDescriptionToJSON(value?: SerdeDescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'preferred': value.preferred,
        'schema': value.schema,
        'additionalProperties': value.additionalProperties,
        'parameters': value.parameters === undefined ? undefined : ((value.parameters as Array<any>).map(SerdeParameterToJSON)),
    };
}

