/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ServerStatus {
    ONLINE = 'ONLINE',
    OFFLINE = 'OFFLINE',
    INITIALIZING = 'INITIALIZING'
}

export function ServerStatusFromJSON(json: any): ServerStatus {
    return ServerStatusFromJSONTyped(json, false);
}

export function ServerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerStatus {
    return json as ServerStatus;
}

export function ServerStatusToJSON(value?: ServerStatus | null): any {
    return value as any;
}

