/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TaskAction {
    RESTART = 'restart'
}

export function TaskActionFromJSON(json: any): TaskAction {
    return TaskActionFromJSONTyped(json, false);
}

export function TaskActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskAction {
    return json as TaskAction;
}

export function TaskActionToJSON(value?: TaskAction | null): any {
    return value as any;
}

