/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TopicPartitionLogdir,
    TopicPartitionLogdirFromJSON,
    TopicPartitionLogdirFromJSONTyped,
    TopicPartitionLogdirToJSON,
} from './';

/**
 * 
 * @export
 * @interface TopicLogdirs
 */
export interface TopicLogdirs {
    /**
     * 
     * @type {string}
     * @memberof TopicLogdirs
     */
    name?: string;
    /**
     * 
     * @type {Array<TopicPartitionLogdir>}
     * @memberof TopicLogdirs
     */
    partitions?: Array<TopicPartitionLogdir>;
}

export function TopicLogdirsFromJSON(json: any): TopicLogdirs {
    return TopicLogdirsFromJSONTyped(json, false);
}

export function TopicLogdirsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicLogdirs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'partitions': !exists(json, 'partitions') ? undefined : ((json['partitions'] as Array<any>).map(TopicPartitionLogdirFromJSON)),
    };
}

export function TopicLogdirsToJSON(value?: TopicLogdirs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'partitions': value.partitions === undefined ? undefined : ((value.partitions as Array<any>).map(TopicPartitionLogdirToJSON)),
    };
}

