/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopicAnalysisProgress
 */
export interface TopicAnalysisProgress {
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisProgress
     */
    startedAt?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisProgress
     */
    completenessPercent?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisProgress
     */
    msgsScanned?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisProgress
     */
    bytesScanned?: number;
}

export function TopicAnalysisProgressFromJSON(json: any): TopicAnalysisProgress {
    return TopicAnalysisProgressFromJSONTyped(json, false);
}

export function TopicAnalysisProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicAnalysisProgress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startedAt': !exists(json, 'startedAt') ? undefined : json['startedAt'],
        'completenessPercent': !exists(json, 'completenessPercent') ? undefined : json['completenessPercent'],
        'msgsScanned': !exists(json, 'msgsScanned') ? undefined : json['msgsScanned'],
        'bytesScanned': !exists(json, 'bytesScanned') ? undefined : json['bytesScanned'],
    };
}

export function TopicAnalysisProgressToJSON(value?: TopicAnalysisProgress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startedAt': value.startedAt,
        'completenessPercent': value.completenessPercent,
        'msgsScanned': value.msgsScanned,
        'bytesScanned': value.bytesScanned,
    };
}

