/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopicUpdate
 */
export interface TopicUpdate {
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof TopicUpdate
     */
    configs?: { [key: string]: string | undefined; };
}

export function TopicUpdateFromJSON(json: any): TopicUpdate {
    return TopicUpdateFromJSONTyped(json, false);
}

export function TopicUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'configs': !exists(json, 'configs') ? undefined : json['configs'],
    };
}

export function TopicUpdateToJSON(value?: TopicUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'configs': value.configs,
    };
}

