/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopicProducerState
 */
export interface TopicProducerState {
    /**
     * 
     * @type {number}
     * @memberof TopicProducerState
     */
    partition?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicProducerState
     */
    producerId?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicProducerState
     */
    producerEpoch?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicProducerState
     */
    lastSequence?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicProducerState
     */
    lastTimestampMs?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicProducerState
     */
    coordinatorEpoch?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicProducerState
     */
    currentTransactionStartOffset?: number;
}

export function TopicProducerStateFromJSON(json: any): TopicProducerState {
    return TopicProducerStateFromJSONTyped(json, false);
}

export function TopicProducerStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicProducerState {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'partition': !exists(json, 'partition') ? undefined : json['partition'],
        'producerId': !exists(json, 'producerId') ? undefined : json['producerId'],
        'producerEpoch': !exists(json, 'producerEpoch') ? undefined : json['producerEpoch'],
        'lastSequence': !exists(json, 'lastSequence') ? undefined : json['lastSequence'],
        'lastTimestampMs': !exists(json, 'lastTimestampMs') ? undefined : json['lastTimestampMs'],
        'coordinatorEpoch': !exists(json, 'coordinatorEpoch') ? undefined : json['coordinatorEpoch'],
        'currentTransactionStartOffset': !exists(json, 'currentTransactionStartOffset') ? undefined : json['currentTransactionStartOffset'],
    };
}

export function TopicProducerStateToJSON(value?: TopicProducerState | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'partition': value.partition,
        'producerId': value.producerId,
        'producerEpoch': value.producerEpoch,
        'lastSequence': value.lastSequence,
        'lastTimestampMs': value.lastTimestampMs,
        'coordinatorEpoch': value.coordinatorEpoch,
        'currentTransactionStartOffset': value.currentTransactionStartOffset,
    };
}

