/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TopicAnalysisStats,
    TopicAnalysisStatsFromJSON,
    TopicAnalysisStatsFromJSONTyped,
    TopicAnalysisStatsToJSON,
} from './';

/**
 * 
 * @export
 * @interface TopicAnalysisResult
 */
export interface TopicAnalysisResult {
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisResult
     */
    startedAt?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisResult
     */
    finishedAt?: number;
    /**
     * 
     * @type {string}
     * @memberof TopicAnalysisResult
     */
    error?: string;
    /**
     * 
     * @type {TopicAnalysisStats}
     * @memberof TopicAnalysisResult
     */
    totalStats?: TopicAnalysisStats;
    /**
     * 
     * @type {Array<TopicAnalysisStats>}
     * @memberof TopicAnalysisResult
     */
    partitionStats?: Array<TopicAnalysisStats>;
}

export function TopicAnalysisResultFromJSON(json: any): TopicAnalysisResult {
    return TopicAnalysisResultFromJSONTyped(json, false);
}

export function TopicAnalysisResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicAnalysisResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startedAt': !exists(json, 'startedAt') ? undefined : json['startedAt'],
        'finishedAt': !exists(json, 'finishedAt') ? undefined : json['finishedAt'],
        'error': !exists(json, 'error') ? undefined : json['error'],
        'totalStats': !exists(json, 'totalStats') ? undefined : TopicAnalysisStatsFromJSON(json['totalStats']),
        'partitionStats': !exists(json, 'partitionStats') ? undefined : ((json['partitionStats'] as Array<any>).map(TopicAnalysisStatsFromJSON)),
    };
}

export function TopicAnalysisResultToJSON(value?: TopicAnalysisResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startedAt': value.startedAt,
        'finishedAt': value.finishedAt,
        'error': value.error,
        'totalStats': TopicAnalysisStatsToJSON(value.totalStats),
        'partitionStats': value.partitionStats === undefined ? undefined : ((value.partitionStats as Array<any>).map(TopicAnalysisStatsToJSON)),
    };
}

