/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SerdeDescription,
    SerdeDescriptionFromJSON,
    SerdeDescriptionFromJSONTyped,
    SerdeDescriptionToJSON,
} from './';

/**
 * 
 * @export
 * @interface TopicSerdeSuggestion
 */
export interface TopicSerdeSuggestion {
    /**
     * 
     * @type {Array<SerdeDescription>}
     * @memberof TopicSerdeSuggestion
     */
    key?: Array<SerdeDescription>;
    /**
     * 
     * @type {Array<SerdeDescription>}
     * @memberof TopicSerdeSuggestion
     */
    value?: Array<SerdeDescription>;
}

export function TopicSerdeSuggestionFromJSON(json: any): TopicSerdeSuggestion {
    return TopicSerdeSuggestionFromJSONTyped(json, false);
}

export function TopicSerdeSuggestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicSerdeSuggestion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : ((json['key'] as Array<any>).map(SerdeDescriptionFromJSON)),
        'value': !exists(json, 'value') ? undefined : ((json['value'] as Array<any>).map(SerdeDescriptionFromJSON)),
    };
}

export function TopicSerdeSuggestionToJSON(value?: TopicSerdeSuggestion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key === undefined ? undefined : ((value.key as Array<any>).map(SerdeDescriptionToJSON)),
        'value': value.value === undefined ? undefined : ((value.value as Array<any>).map(SerdeDescriptionToJSON)),
    };
}

