/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TopicColumnsToSort {
    NAME = 'NAME',
    OUT_OF_SYNC_REPLICAS = 'OUT_OF_SYNC_REPLICAS',
    TOTAL_PARTITIONS = 'TOTAL_PARTITIONS',
    REPLICATION_FACTOR = 'REPLICATION_FACTOR',
    SIZE = 'SIZE',
    MESSAGES_COUNT = 'MESSAGES_COUNT'
}

export function TopicColumnsToSortFromJSON(json: any): TopicColumnsToSort {
    return TopicColumnsToSortFromJSONTyped(json, false);
}

export function TopicColumnsToSortFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicColumnsToSort {
    return json as TopicColumnsToSort;
}

export function TopicColumnsToSortToJSON(value?: TopicColumnsToSort | null): any {
    return value as any;
}

