/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MessageFormat,
    MessageFormatFromJSON,
    MessageFormatFromJSONTyped,
    MessageFormatToJSON,
} from './';

/**
 * 
 * @export
 * @interface TopicMessage
 */
export interface TopicMessage {
    /**
     * 
     * @type {number}
     * @memberof TopicMessage
     */
    partition: number;
    /**
     * 
     * @type {number}
     * @memberof TopicMessage
     */
    offset: number;
    /**
     * 
     * @type {Date}
     * @memberof TopicMessage
     */
    timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof TopicMessage
     */
    timestampType?: TopicMessageTimestampTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TopicMessage
     */
    key?: string;
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof TopicMessage
     */
    headers?: { [key: string]: string | undefined; };
    /**
     * 
     * @type {string}
     * @memberof TopicMessage
     */
    value?: string;
    /**
     * 
     * @type {MessageFormat}
     * @memberof TopicMessage
     */
    keyFormat?: MessageFormat | null;
    /**
     * 
     * @type {MessageFormat}
     * @memberof TopicMessage
     */
    valueFormat?: MessageFormat | null;
    /**
     * 
     * @type {number}
     * @memberof TopicMessage
     */
    keySize?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicMessage
     */
    valueSize?: number;
    /**
     * 
     * @type {string}
     * @memberof TopicMessage
     */
    keySchemaId?: string;
    /**
     * 
     * @type {string}
     * @memberof TopicMessage
     */
    valueSchemaId?: string;
    /**
     * 
     * @type {number}
     * @memberof TopicMessage
     */
    headersSize?: number;
    /**
     * 
     * @type {string}
     * @memberof TopicMessage
     */
    keySerde?: string;
    /**
     * 
     * @type {string}
     * @memberof TopicMessage
     */
    valueSerde?: string;
    /**
     * 
     * @type {{ [key: string]: any | undefined; }}
     * @memberof TopicMessage
     */
    keyDeserializeProperties?: { [key: string]: any | undefined; };
    /**
     * 
     * @type {{ [key: string]: any | undefined; }}
     * @memberof TopicMessage
     */
    valueDeserializeProperties?: { [key: string]: any | undefined; };
}

/**
* @export
* @enum {string}
*/
export enum TopicMessageTimestampTypeEnum {
    NO_TIMESTAMP_TYPE = 'NO_TIMESTAMP_TYPE',
    CREATE_TIME = 'CREATE_TIME',
    LOG_APPEND_TIME = 'LOG_APPEND_TIME'
}

export function TopicMessageFromJSON(json: any): TopicMessage {
    return TopicMessageFromJSONTyped(json, false);
}

export function TopicMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'partition': json['partition'],
        'offset': json['offset'],
        'timestamp': (new Date(json['timestamp'])),
        'timestampType': !exists(json, 'timestampType') ? undefined : json['timestampType'],
        'key': !exists(json, 'key') ? undefined : json['key'],
        'headers': !exists(json, 'headers') ? undefined : json['headers'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'keyFormat': !exists(json, 'keyFormat') ? undefined : MessageFormatFromJSON(json['keyFormat']),
        'valueFormat': !exists(json, 'valueFormat') ? undefined : MessageFormatFromJSON(json['valueFormat']),
        'keySize': !exists(json, 'keySize') ? undefined : json['keySize'],
        'valueSize': !exists(json, 'valueSize') ? undefined : json['valueSize'],
        'keySchemaId': !exists(json, 'keySchemaId') ? undefined : json['keySchemaId'],
        'valueSchemaId': !exists(json, 'valueSchemaId') ? undefined : json['valueSchemaId'],
        'headersSize': !exists(json, 'headersSize') ? undefined : json['headersSize'],
        'keySerde': !exists(json, 'keySerde') ? undefined : json['keySerde'],
        'valueSerde': !exists(json, 'valueSerde') ? undefined : json['valueSerde'],
        'keyDeserializeProperties': !exists(json, 'keyDeserializeProperties') ? undefined : json['keyDeserializeProperties'],
        'valueDeserializeProperties': !exists(json, 'valueDeserializeProperties') ? undefined : json['valueDeserializeProperties'],
    };
}

export function TopicMessageToJSON(value?: TopicMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'partition': value.partition,
        'offset': value.offset,
        'timestamp': (value.timestamp.toISOString()),
        'timestampType': value.timestampType,
        'key': value.key,
        'headers': value.headers,
        'value': value.value,
        'keyFormat': MessageFormatToJSON(value.keyFormat),
        'valueFormat': MessageFormatToJSON(value.valueFormat),
        'keySize': value.keySize,
        'valueSize': value.valueSize,
        'keySchemaId': value.keySchemaId,
        'valueSchemaId': value.valueSchemaId,
        'headersSize': value.headersSize,
        'keySerde': value.keySerde,
        'valueSerde': value.valueSerde,
        'keyDeserializeProperties': value.keyDeserializeProperties,
        'valueDeserializeProperties': value.valueDeserializeProperties,
    };
}

