/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TopicAnalysisSizeStats,
    TopicAnalysisSizeStatsFromJSON,
    TopicAnalysisSizeStatsFromJSONTyped,
    TopicAnalysisSizeStatsToJSON,
    TopicAnalysisStatsHourlyMsgCounts,
    TopicAnalysisStatsHourlyMsgCountsFromJSON,
    TopicAnalysisStatsHourlyMsgCountsFromJSONTyped,
    TopicAnalysisStatsHourlyMsgCountsToJSON,
} from './';

/**
 * 
 * @export
 * @interface TopicAnalysisStats
 */
export interface TopicAnalysisStats {
    /**
     * null if this is total stats
     * @type {number}
     * @memberof TopicAnalysisStats
     */
    partition?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisStats
     */
    totalMsgs?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisStats
     */
    minOffset?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisStats
     */
    maxOffset?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisStats
     */
    minTimestamp?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisStats
     */
    maxTimestamp?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisStats
     */
    nullKeys?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisStats
     */
    nullValues?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisStats
     */
    approxUniqKeys?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisStats
     */
    approxUniqValues?: number;
    /**
     * 
     * @type {TopicAnalysisSizeStats}
     * @memberof TopicAnalysisStats
     */
    keySize?: TopicAnalysisSizeStats;
    /**
     * 
     * @type {TopicAnalysisSizeStats}
     * @memberof TopicAnalysisStats
     */
    valueSize?: TopicAnalysisSizeStats;
    /**
     * 
     * @type {Array<TopicAnalysisStatsHourlyMsgCounts>}
     * @memberof TopicAnalysisStats
     */
    hourlyMsgCounts?: Array<TopicAnalysisStatsHourlyMsgCounts>;
}

export function TopicAnalysisStatsFromJSON(json: any): TopicAnalysisStats {
    return TopicAnalysisStatsFromJSONTyped(json, false);
}

export function TopicAnalysisStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicAnalysisStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'partition': !exists(json, 'partition') ? undefined : json['partition'],
        'totalMsgs': !exists(json, 'totalMsgs') ? undefined : json['totalMsgs'],
        'minOffset': !exists(json, 'minOffset') ? undefined : json['minOffset'],
        'maxOffset': !exists(json, 'maxOffset') ? undefined : json['maxOffset'],
        'minTimestamp': !exists(json, 'minTimestamp') ? undefined : json['minTimestamp'],
        'maxTimestamp': !exists(json, 'maxTimestamp') ? undefined : json['maxTimestamp'],
        'nullKeys': !exists(json, 'nullKeys') ? undefined : json['nullKeys'],
        'nullValues': !exists(json, 'nullValues') ? undefined : json['nullValues'],
        'approxUniqKeys': !exists(json, 'approxUniqKeys') ? undefined : json['approxUniqKeys'],
        'approxUniqValues': !exists(json, 'approxUniqValues') ? undefined : json['approxUniqValues'],
        'keySize': !exists(json, 'keySize') ? undefined : TopicAnalysisSizeStatsFromJSON(json['keySize']),
        'valueSize': !exists(json, 'valueSize') ? undefined : TopicAnalysisSizeStatsFromJSON(json['valueSize']),
        'hourlyMsgCounts': !exists(json, 'hourlyMsgCounts') ? undefined : ((json['hourlyMsgCounts'] as Array<any>).map(TopicAnalysisStatsHourlyMsgCountsFromJSON)),
    };
}

export function TopicAnalysisStatsToJSON(value?: TopicAnalysisStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'partition': value.partition,
        'totalMsgs': value.totalMsgs,
        'minOffset': value.minOffset,
        'maxOffset': value.maxOffset,
        'minTimestamp': value.minTimestamp,
        'maxTimestamp': value.maxTimestamp,
        'nullKeys': value.nullKeys,
        'nullValues': value.nullValues,
        'approxUniqKeys': value.approxUniqKeys,
        'approxUniqValues': value.approxUniqValues,
        'keySize': TopicAnalysisSizeStatsToJSON(value.keySize),
        'valueSize': TopicAnalysisSizeStatsToJSON(value.valueSize),
        'hourlyMsgCounts': value.hourlyMsgCounts === undefined ? undefined : ((value.hourlyMsgCounts as Array<any>).map(TopicAnalysisStatsHourlyMsgCountsToJSON)),
    };
}

