/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopicCreation
 */
export interface TopicCreation {
    /**
     * 
     * @type {string}
     * @memberof TopicCreation
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof TopicCreation
     */
    partitions: number;
    /**
     * 
     * @type {number}
     * @memberof TopicCreation
     */
    replicationFactor?: number;
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof TopicCreation
     */
    configs?: { [key: string]: string | undefined; };
}

export function TopicCreationFromJSON(json: any): TopicCreation {
    return TopicCreationFromJSONTyped(json, false);
}

export function TopicCreationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicCreation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'partitions': json['partitions'],
        'replicationFactor': !exists(json, 'replicationFactor') ? undefined : json['replicationFactor'],
        'configs': !exists(json, 'configs') ? undefined : json['configs'],
    };
}

export function TopicCreationToJSON(value?: TopicCreation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'partitions': value.partitions,
        'replicationFactor': value.replicationFactor,
        'configs': value.configs,
    };
}

