/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopicPartitionLogdir
 */
export interface TopicPartitionLogdir {
    /**
     * 
     * @type {number}
     * @memberof TopicPartitionLogdir
     */
    partition?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicPartitionLogdir
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicPartitionLogdir
     */
    offsetLag?: number;
}

export function TopicPartitionLogdirFromJSON(json: any): TopicPartitionLogdir {
    return TopicPartitionLogdirFromJSONTyped(json, false);
}

export function TopicPartitionLogdirFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicPartitionLogdir {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'partition': !exists(json, 'partition') ? undefined : json['partition'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'offsetLag': !exists(json, 'offsetLag') ? undefined : json['offsetLag'],
    };
}

export function TopicPartitionLogdirToJSON(value?: TopicPartitionLogdir | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'partition': value.partition,
        'size': value.size,
        'offsetLag': value.offsetLag,
    };
}

