/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TopicMessage,
    TopicMessageFromJSON,
    TopicMessageFromJSONTyped,
    TopicMessageToJSON,
    TopicMessageConsuming,
    TopicMessageConsumingFromJSON,
    TopicMessageConsumingFromJSONTyped,
    TopicMessageConsumingToJSON,
    TopicMessageNextPageCursor,
    TopicMessageNextPageCursorFromJSON,
    TopicMessageNextPageCursorFromJSONTyped,
    TopicMessageNextPageCursorToJSON,
    TopicMessagePhase,
    TopicMessagePhaseFromJSON,
    TopicMessagePhaseFromJSONTyped,
    TopicMessagePhaseToJSON,
} from './';

/**
 * 
 * @export
 * @interface TopicMessageEvent
 */
export interface TopicMessageEvent {
    /**
     * 
     * @type {string}
     * @memberof TopicMessageEvent
     */
    type?: TopicMessageEventTypeEnum;
    /**
     * 
     * @type {TopicMessage}
     * @memberof TopicMessageEvent
     */
    message?: TopicMessage;
    /**
     * 
     * @type {TopicMessagePhase}
     * @memberof TopicMessageEvent
     */
    phase?: TopicMessagePhase;
    /**
     * 
     * @type {TopicMessageConsuming}
     * @memberof TopicMessageEvent
     */
    consuming?: TopicMessageConsuming;
    /**
     * 
     * @type {TopicMessageNextPageCursor}
     * @memberof TopicMessageEvent
     */
    cursor?: TopicMessageNextPageCursor;
}

/**
* @export
* @enum {string}
*/
export enum TopicMessageEventTypeEnum {
    PHASE = 'PHASE',
    MESSAGE = 'MESSAGE',
    CONSUMING = 'CONSUMING',
    DONE = 'DONE'
}

export function TopicMessageEventFromJSON(json: any): TopicMessageEvent {
    return TopicMessageEventFromJSONTyped(json, false);
}

export function TopicMessageEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicMessageEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'message': !exists(json, 'message') ? undefined : TopicMessageFromJSON(json['message']),
        'phase': !exists(json, 'phase') ? undefined : TopicMessagePhaseFromJSON(json['phase']),
        'consuming': !exists(json, 'consuming') ? undefined : TopicMessageConsumingFromJSON(json['consuming']),
        'cursor': !exists(json, 'cursor') ? undefined : TopicMessageNextPageCursorFromJSON(json['cursor']),
    };
}

export function TopicMessageEventToJSON(value?: TopicMessageEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'message': TopicMessageToJSON(value.message),
        'phase': TopicMessagePhaseToJSON(value.phase),
        'consuming': TopicMessageConsumingToJSON(value.consuming),
        'cursor': TopicMessageNextPageCursorToJSON(value.cursor),
    };
}

