/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopicAnalysisSizeStats
 */
export interface TopicAnalysisSizeStats {
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisSizeStats
     */
    sum?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisSizeStats
     */
    min?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisSizeStats
     */
    max?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisSizeStats
     */
    avg?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisSizeStats
     */
    prctl50?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisSizeStats
     */
    prctl75?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisSizeStats
     */
    prctl95?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisSizeStats
     */
    prctl99?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicAnalysisSizeStats
     */
    prctl999?: number;
}

export function TopicAnalysisSizeStatsFromJSON(json: any): TopicAnalysisSizeStats {
    return TopicAnalysisSizeStatsFromJSONTyped(json, false);
}

export function TopicAnalysisSizeStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicAnalysisSizeStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sum': !exists(json, 'sum') ? undefined : json['sum'],
        'min': !exists(json, 'min') ? undefined : json['min'],
        'max': !exists(json, 'max') ? undefined : json['max'],
        'avg': !exists(json, 'avg') ? undefined : json['avg'],
        'prctl50': !exists(json, 'prctl50') ? undefined : json['prctl50'],
        'prctl75': !exists(json, 'prctl75') ? undefined : json['prctl75'],
        'prctl95': !exists(json, 'prctl95') ? undefined : json['prctl95'],
        'prctl99': !exists(json, 'prctl99') ? undefined : json['prctl99'],
        'prctl999': !exists(json, 'prctl999') ? undefined : json['prctl999'],
    };
}

export function TopicAnalysisSizeStatsToJSON(value?: TopicAnalysisSizeStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sum': value.sum,
        'min': value.min,
        'max': value.max,
        'avg': value.avg,
        'prctl50': value.prctl50,
        'prctl75': value.prctl75,
        'prctl95': value.prctl95,
        'prctl99': value.prctl99,
        'prctl999': value.prctl999,
    };
}

