/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopicMessageNextPageCursor
 */
export interface TopicMessageNextPageCursor {
    /**
     * 
     * @type {string}
     * @memberof TopicMessageNextPageCursor
     */
    id?: string;
}

export function TopicMessageNextPageCursorFromJSON(json: any): TopicMessageNextPageCursor {
    return TopicMessageNextPageCursorFromJSONTyped(json, false);
}

export function TopicMessageNextPageCursorFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicMessageNextPageCursor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function TopicMessageNextPageCursorToJSON(value?: TopicMessageNextPageCursor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

