/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadedFileInfo
 */
export interface UploadedFileInfo {
    /**
     * 
     * @type {string}
     * @memberof UploadedFileInfo
     */
    location: string;
}

export function UploadedFileInfoFromJSON(json: any): UploadedFileInfo {
    return UploadedFileInfoFromJSONTyped(json, false);
}

export function UploadedFileInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadedFileInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'location': json['location'],
    };
}

export function UploadedFileInfoToJSON(value?: UploadedFileInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'location': value.location,
    };
}

