/* tslint:disable */
/* eslint-disable */
/**
 * Kafbat UI Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: support@kafbat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Action,
    ActionFromJSON,
    ActionFromJSONTyped,
    ActionToJSON,
    ResourceType,
    ResourceTypeFromJSON,
    ResourceTypeFromJSONTyped,
    ResourceTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserPermission
 */
export interface UserPermission {
    /**
     * 
     * @type {Array<string>}
     * @memberof UserPermission
     */
    clusters: Array<string>;
    /**
     * 
     * @type {ResourceType}
     * @memberof UserPermission
     */
    resource: ResourceType;
    /**
     * 
     * @type {string}
     * @memberof UserPermission
     */
    value?: string;
    /**
     * 
     * @type {Array<Action>}
     * @memberof UserPermission
     */
    actions: Array<Action>;
}

export function UserPermissionFromJSON(json: any): UserPermission {
    return UserPermissionFromJSONTyped(json, false);
}

export function UserPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPermission {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clusters': json['clusters'],
        'resource': ResourceTypeFromJSON(json['resource']),
        'value': !exists(json, 'value') ? undefined : json['value'],
        'actions': ((json['actions'] as Array<any>).map(ActionFromJSON)),
    };
}

export function UserPermissionToJSON(value?: UserPermission | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clusters': value.clusters,
        'resource': ResourceTypeToJSON(value.resource),
        'value': value.value,
        'actions': ((value.actions as Array<any>).map(ActionToJSON)),
    };
}

